query CompoundQuery($criteria: CompoundQueryInput!) {
  compoundQuery(query: $criteria) {
    trackIds
    counts {
      singer {
        name
        count
      }
      orchestra {
        name
        count
      }
      genre {
        name
        count
      }
    }
  }
}