import { SimpleTrack } from './types.entity';

export const testTracks: SimpleTrack[] = [
  {
    title: 'Ki-Ki',
    genre: 'tango',
    trackId: 0,
    // orchestra: ['Francisco Canaro'], corrupting cause I need to test handling of indexing no orchestra
    year: 1924,

  },
  {
    title: 'Kicho',
    genre: 'tango',
    trackId: 1,
    // orchestra: ['Ensemble Hyperion'], corrupting cause I need to test handling of indexing no orchestra
    secondsLong: 386,
    year: 2008,

  },
  {
    title: 'Katinka',
    genre: 'fox trot',
    trackId: 2,
    // orchestra: ['Francisco Canaro'], corrupting cause I need to test handling of indexing no orchestra
    secondsLong: 162,
    year: 1926,
  },
  {
    title: 'Kiti - kiti',
    genre: 'shimmy',
    trackId: 3,
    orchestra: ['Roberto Firpo'],
    year: 1922,
  },
  {
    title: 'Knock-out de amor',
    genre: 'tango',
    trackId: 3,
    orchestra: [
      'Ángel Domingo Riverol',
      'Guillermo Barbieri',
      'José María Aguilar',
    ],
    singer: ['Carlos Gardel'],
    secondsLong: 147,
    year: 1930,
  },
  {
    title: 'B.B.',
    genre: 'tango',
    trackId: 4,
    orchestra: ['Selección Nacional'],
    secondsLong: 187,
    year: 2005,
  },
  {
    title: 'Bacán',
    genre: 'tango',
    trackId: 5,
    orchestra: ['Osvaldo Fresedo'],
    secondsLong: 161,
    year: 1926,
  },
  {
    title: 'B.B.',
    genre: 'tango',
    trackId: 6,
    orchestra: ['Aníbal Troilo'],
    secondsLong: 205,
    year: 1963,
  },
  {
    title: 'Bacán fulero',
    genre: 'tango',
    trackId: 7,
    orchestra: ['Francisco Lomuto'],
    secondsLong: 174,
    year: 1927,
  },
  {
    title: 'Baby face',
    genre: 'fox trot',
    trackId: 8,
    orchestra: ['Francisco Canaro'],
    secondsLong: 175,
    year: 1927,
  },
  {
    title: 'Kri kri',
    genre: 'fox trot',
    trackId: 9,
    orchestra: ['Adolfo Carabelli'],
    singer: ['Jaime Moreno'],
    secondsLong: 213,
    year: 1930,
  },
  {
    title: 'Bacan fulero',
    genre: 'tango',
    trackId: 10,
    orchestra: ['Roberto Firpo'],
    secondsLong: 177,
    year: 1929,
  },
  {
    title: 'Bach',
    genre: '',
    trackId: 11,
    orchestra: ['Trio Neuklang'],
    secondsLong: 195,
    year: 2013,
  },
  {
    title: 'Bahía Blanca',
    genre: 'tango',
    trackId: 12,
    orchestra: ['Florindo Sassone'],
    secondsLong: 176,
    year: 1959,
  },
  {
    title: 'Bachicha',
    genre: 'tango',
    trackId: 13,
    orchestra: ['Cayetano Puglisi'],
    secondsLong: 164,
    year: 1930,
  },
  {
    title: 'Bahía Blanca',
    genre: 'tango',
    trackId: 14,
    orchestra: ['Horacio Salgán', 'Ubaldo Aquiles De Lio'],
    secondsLong: 159,
    year: 1971,
  },
  {
    title: 'Bahía Blanca',
    genre: 'tango',
    trackId: 15,
    orchestra: ['Carlos Di Sarli'],
    secondsLong: 170,
    year: 1958,
  },
  {
    title: 'Bahía Blanca',
    genre: 'tango',
    trackId: 16,
    orchestra: ['Osvaldo Fresedo'],
    secondsLong: 174,
    year: 1961,
  },
  {
    title: 'Bahía Blanca',
    genre: 'tango',
    trackId: 17,
    orchestra: ['Selección Nacional'],
    secondsLong: 197,
    year: 2005,
  },
  {
    title: 'Bahía Blanca',
    genre: 'tango',
    trackId: 18,
    orchestra: ['Carlos Di Sarli'],
    secondsLong: 170,
    year: 1957,
  },
];
