query TrackDetailsBatch($ids: [Float!]!) {
  tracksByIds(ids: $ids) {
    ...TrackDetailFragment
  }
}

fragment TrackDetailFragment on SimpleTrack {
  id
  title
  genre
  singer
  orchestra
  secondsLong
  year
  linkScore
  link {
    description
    title
    videoId
  }
}
