import { CompoundQueryQuery } from '../../../generated/graphql';

export const compoundQuery: CompoundQueryQuery = {
  compoundQuery: {
    ids: [
      '10688',
      '10699',
      '10696',
      '10701',
      '10700',
      '10708',
      '10698',
      '10702',
      '10703',
      '10707',
      '10710',
      '10711',
      '10712',
      '10713',
      '10714',
      '10715',
      '10727',
      '10729',
      '10733',
      '10732',
    ],
    randomId: '18771',
    page: 0,
    totalPages: 1217,
    totalResults: 24323,
    counts: {
      year: [
        { name: '1930', count: 1560, __typename: 'CountTuple' },
        { name: '1927', count: 1342, __typename: 'CountTuple' },
        { name: '1928', count: 1306, __typename: 'CountTuple' },
        { name: '1929', count: 1296, __typename: 'CountTuple' },
        { name: '1931', count: 878, __typename: 'CountTuple' },
        { name: '1952', count: 617, __typename: 'CountTuple' },
        { name: '1932', count: 612, __typename: 'CountTuple' },
        { name: '1926', count: 554, __typename: 'CountTuple' },
        { name: '1950', count: 550, __typename: 'CountTuple' },
        { name: '1953', count: 527, __typename: 'CountTuple' },
        { name: '1942', count: 471, __typename: 'CountTuple' },
        { name: '1933', count: 462, __typename: 'CountTuple' },
        { name: '1951', count: 459, __typename: 'CountTuple' },
        { name: '1954', count: 457, __typename: 'CountTuple' },
        { name: '1944', count: 457, __typename: 'CountTuple' },
        { name: '1956', count: 454, __typename: 'CountTuple' },
        { name: '1943', count: 430, __typename: 'CountTuple' },
        { name: '1941', count: 428, __typename: 'CountTuple' },
        { name: '1945', count: 419, __typename: 'CountTuple' },
        { name: '1955', count: 408, __typename: 'CountTuple' },
        { name: '1946', count: 406, __typename: 'CountTuple' },
        { name: '1938', count: 395, __typename: 'CountTuple' },
        { name: '1957', count: 394, __typename: 'CountTuple' },
        { name: '1937', count: 382, __typename: 'CountTuple' },
        { name: '1936', count: 371, __typename: 'CountTuple' },
        { name: '1958', count: 361, __typename: 'CountTuple' },
        { name: '1934', count: 361, __typename: 'CountTuple' },
        { name: '1935', count: 352, __typename: 'CountTuple' },
        { name: '1939', count: 334, __typename: 'CountTuple' },
        { name: '1959', count: 333, __typename: 'CountTuple' },
        { name: '1940', count: 333, __typename: 'CountTuple' },
        { name: '1925', count: 333, __typename: 'CountTuple' },
        { name: '1961', count: 319, __typename: 'CountTuple' },
        { name: '1947', count: 308, __typename: 'CountTuple' },
        { name: '1949', count: 269, __typename: 'CountTuple' },
        { name: '1968', count: 261, __typename: 'CountTuple' },
        { name: '1960', count: 254, __typename: 'CountTuple' },
        { name: '1923', count: 239, __typename: 'CountTuple' },
        { name: '1962', count: 233, __typename: 'CountTuple' },
        { name: '1966', count: 230, __typename: 'CountTuple' },
        { name: '1967', count: 228, __typename: 'CountTuple' },
        { name: '1965', count: 226, __typename: 'CountTuple' },
        { name: '1963', count: 221, __typename: 'CountTuple' },
        { name: '1948', count: 219, __typename: 'CountTuple' },
        { name: '1924', count: 201, __typename: 'CountTuple' },
        { name: '1964', count: 201, __typename: 'CountTuple' },
        { name: '1970', count: 193, __typename: 'CountTuple' },
        { name: '1969', count: 183, __typename: 'CountTuple' },
        { name: '1922', count: 152, __typename: 'CountTuple' },
        { name: '1920', count: 136, __typename: 'CountTuple' },
        { name: '1972', count: 124, __typename: 'CountTuple' },
        { name: '1917', count: 122, __typename: 'CountTuple' },
        { name: '1973', count: 116, __typename: 'CountTuple' },
        { name: '1974', count: 116, __typename: 'CountTuple' },
        { name: '1971', count: 99, __typename: 'CountTuple' },
        { name: '1975', count: 95, __typename: 'CountTuple' },
        { name: '1983', count: 83, __typename: 'CountTuple' },
        { name: '1981', count: 81, __typename: 'CountTuple' },
        { name: '2005', count: 77, __typename: 'CountTuple' },
        { name: '1980', count: 73, __typename: 'CountTuple' },
        { name: '1979', count: 68, __typename: 'CountTuple' },
        { name: '1998', count: 61, __typename: 'CountTuple' },
        { name: '1912', count: 60, __typename: 'CountTuple' },
        { name: '2009', count: 57, __typename: 'CountTuple' },
        { name: '1977', count: 49, __typename: 'CountTuple' },
        { name: '1989', count: 44, __typename: 'CountTuple' },
        { name: '1985', count: 44, __typename: 'CountTuple' },
        { name: '1921', count: 44, __typename: 'CountTuple' },
        { name: '1996', count: 44, __typename: 'CountTuple' },
        { name: '1982', count: 40, __typename: 'CountTuple' },
        { name: '1976', count: 40, __typename: 'CountTuple' },
        { name: '2006', count: 37, __typename: 'CountTuple' },
        { name: '2010', count: 37, __typename: 'CountTuple' },
        { name: '2003', count: 36, __typename: 'CountTuple' },
        { name: '1999', count: 34, __typename: 'CountTuple' },
        { name: '1914', count: 34, __typename: 'CountTuple' },
        { name: '2004', count: 34, __typename: 'CountTuple' },
        { name: '1997', count: 33, __typename: 'CountTuple' },
        { name: '2001', count: 31, __typename: 'CountTuple' },
        { name: '1984', count: 30, __typename: 'CountTuple' },
        { name: '1919', count: 28, __typename: 'CountTuple' },
        { name: '2012', count: 27, __typename: 'CountTuple' },
        { name: '1978', count: 26, __typename: 'CountTuple' },
        { name: '2008', count: 25, __typename: 'CountTuple' },
        { name: '2000', count: 24, __typename: 'CountTuple' },
        { name: '1918', count: 23, __typename: 'CountTuple' },
        { name: '1916', count: 23, __typename: 'CountTuple' },
        { name: '2007', count: 22, __typename: 'CountTuple' },
        { name: '1913', count: 20, __typename: 'CountTuple' },
        { name: '1995', count: 19, __typename: 'CountTuple' },
        { name: '1986', count: 18, __typename: 'CountTuple' },
        { name: '1900', count: 16, __typename: 'CountTuple' },
        { name: '2013', count: 13, __typename: 'CountTuple' },
        { name: '1915', count: 10, __typename: 'CountTuple' },
        { name: '1911', count: 9, __typename: 'CountTuple' },
        { name: '1993', count: 9, __typename: 'CountTuple' },
        { name: '1910', count: 9, __typename: 'CountTuple' },
        { name: '1909', count: 8, __typename: 'CountTuple' },
        { name: '1987', count: 6, __typename: 'CountTuple' },
        { name: '1991', count: 5, __typename: 'CountTuple' },
        { name: '1992', count: 4, __typename: 'CountTuple' },
        { name: '1988', count: 4, __typename: 'CountTuple' },
        { name: '1990', count: 4, __typename: 'CountTuple' },
        { name: '1907', count: 3, __typename: 'CountTuple' },
        { name: '1994', count: 2, __typename: 'CountTuple' },
        { name: '2002', count: 2, __typename: 'CountTuple' },
        { name: '2016', count: 2, __typename: 'CountTuple' },
        { name: '1906', count: 1, __typename: 'CountTuple' },
        { name: '1905', count: 1, __typename: 'CountTuple' },
      ],
      singer: [
        { name: 'Instrumental', count: 9250, __typename: 'CountTuple' },
        { name: 'Carlos Gardel', count: 1090, __typename: 'CountTuple' },
        { name: 'Charlo', count: 900, __typename: 'CountTuple' },
        { name: 'Ernesto Famá', count: 341, __typename: 'CountTuple' },
        { name: 'Luis Díaz', count: 314, __typename: 'CountTuple' },
        { name: 'Alberto Castillo', count: 314, __typename: 'CountTuple' },
        { name: 'Mercedes Simone', count: 288, __typename: 'CountTuple' },
        { name: 'Agustín Magaldi', count: 241, __typename: 'CountTuple' },
        { name: 'Carlos Dante', count: 235, __typename: 'CountTuple' },
        { name: 'Teófilo Ibáñez', count: 229, __typename: 'CountTuple' },
        { name: 'Roberto Maida', count: 227, __typename: 'CountTuple' },
        { name: 'Azucena Maizani', count: 221, __typename: 'CountTuple' },
        { name: 'Ignacio Corsini', count: 219, __typename: 'CountTuple' },
        { name: 'Ángel Vargas', count: 213, __typename: 'CountTuple' },
        { name: 'Armando Moreno', count: 211, __typename: 'CountTuple' },
        { name: 'Roberto Goyeneche', count: 209, __typename: 'CountTuple' },
        { name: 'Ada Falcón', count: 194, __typename: 'CountTuple' },
        { name: 'Libertad Lamarque', count: 194, __typename: 'CountTuple' },
        { name: 'Fernando Díaz', count: 185, __typename: 'CountTuple' },
        { name: 'Alberto Gómez', count: 182, __typename: 'CountTuple' },
        { name: 'Armando Laborde', count: 173, __typename: 'CountTuple' },
        { name: 'Alberto Marino', count: 170, __typename: 'CountTuple' },
        { name: 'Roberto Rufino', count: 156, __typename: 'CountTuple' },
        { name: 'Julio Sosa', count: 153, __typename: 'CountTuple' },
        { name: 'Agustín Irusta', count: 153, __typename: 'CountTuple' },
        { name: 'Alberto Echagüe', count: 152, __typename: 'CountTuple' },
        {
          name: 'Francisco Fiorentino',
          count: 150,
          __typename: 'CountTuple',
        },
        { name: 'Jorge Omar', count: 147, __typename: 'CountTuple' },
        { name: 'Rosita Quiroga', count: 145, __typename: 'CountTuple' },
        { name: 'Alberto Podestá', count: 142, __typename: 'CountTuple' },
        { name: 'Carlos Viván', count: 138, __typename: 'CountTuple' },
        { name: 'Edmundo Rivero', count: 123, __typename: 'CountTuple' },
        { name: 'Carlos A. Varela', count: 122, __typename: 'CountTuple' },
        { name: 'Carlos Roldán', count: 121, __typename: 'CountTuple' },
        { name: 'Nelly Omar', count: 120, __typename: 'CountTuple' },
        { name: 'Jorge Maciel', count: 116, __typename: 'CountTuple' },
        { name: 'Floreal Ruíz', count: 115, __typename: 'CountTuple' },
        { name: 'Jorge Valdez', count: 115, __typename: 'CountTuple' },
        { name: 'Roberto Díaz', count: 111, __typename: 'CountTuple' },
        { name: 'Oscar Serpa', count: 105, __typename: 'CountTuple' },
        { name: 'Hugo del Carril', count: 104, __typename: 'CountTuple' },
        { name: 'Oscar Larroca', count: 101, __typename: 'CountTuple' },
        { name: 'Carlos Lafuente', count: 100, __typename: 'CountTuple' },
        { name: 'Héctor Mauré', count: 96, __typename: 'CountTuple' },
        { name: 'José Razzano', count: 93, __typename: 'CountTuple' },
        { name: 'Raúl Berón', count: 91, __typename: 'CountTuple' },
        { name: 'Argentino Ledesma', count: 89, __typename: 'CountTuple' },
        { name: 'Ranko Fujisawa', count: 89, __typename: 'CountTuple' },
        { name: 'Enrique Campos', count: 85, __typename: 'CountTuple' },
        { name: 'Roberto Ray', count: 85, __typename: 'CountTuple' },
        { name: 'Alberto Arenas', count: 82, __typename: 'CountTuple' },
        { name: 'Alberto Morán', count: 81, __typename: 'CountTuple' },
        { name: 'Horacio Lagos', count: 79, __typename: 'CountTuple' },
        { name: 'Tita Merello', count: 79, __typename: 'CountTuple' },
        { name: 'Jorge Durán', count: 75, __typename: 'CountTuple' },
        { name: 'Tania', count: 73, __typename: 'CountTuple' },
        { name: 'Abel Córdoba', count: 70, __typename: 'CountTuple' },
        { name: 'Julio Martel', count: 69, __typename: 'CountTuple' },
        { name: 'Osvaldo Ramos', count: 67, __typename: 'CountTuple' },
        { name: 'Raúl Iriarte', count: 66, __typename: 'CountTuple' },
        { name: 'Imperio Argentina', count: 65, __typename: 'CountTuple' },
        { name: 'Luis Scalón', count: 63, __typename: 'CountTuple' },
        { name: 'Juan Carlos Godoy', count: 62, __typename: 'CountTuple' },
        { name: 'Roberto Fugazot', count: 61, __typename: 'CountTuple' },
        { name: 'Unspecified Male', count: 60, __typename: 'CountTuple' },
        { name: 'Alfredo Belusi', count: 60, __typename: 'CountTuple' },
        { name: 'Francisco Amor', count: 59, __typename: 'CountTuple' },
        { name: 'Jorge Vidal', count: 57, __typename: 'CountTuple' },
        { name: 'Mario Bustos', count: 57, __typename: 'CountTuple' },
        { name: 'Roberto Chanel', count: 53, __typename: 'CountTuple' },
        { name: 'Mario Pomar', count: 52, __typename: 'CountTuple' },
        { name: 'Príncipe Azul', count: 51, __typename: 'CountTuple' },
        { name: 'Jorge Ortiz', count: 51, __typename: 'CountTuple' },
        { name: 'Alberto Vila', count: 50, __typename: 'CountTuple' },
        { name: 'Luis Mendoza', count: 49, __typename: 'CountTuple' },
        { name: 'Jorge Casal', count: 48, __typename: 'CountTuple' },
        { name: 'Ricardo Ruiz', count: 48, __typename: 'CountTuple' },
        { name: 'Alberto Rivera', count: 48, __typename: 'CountTuple' },
        { name: 'Pedro Noda', count: 48, __typename: 'CountTuple' },
        { name: '', count: 47, __typename: 'CountTuple' },
        { name: 'Eduardo Adrián', count: 46, __typename: 'CountTuple' },
        { name: 'Rodolfo Lesica', count: 46, __typename: 'CountTuple' },
        { name: 'Susana Rinaldi', count: 45, __typename: 'CountTuple' },
        { name: 'Antonio Buglione', count: 42, __typename: 'CountTuple' },
        { name: 'Roberto Florio', count: 41, __typename: 'CountTuple' },
        { name: 'Miguel Montero', count: 41, __typename: 'CountTuple' },
        { name: 'Héctor Pacheco', count: 41, __typename: 'CountTuple' },
        { name: 'Horacio Palma', count: 40, __typename: 'CountTuple' },
        { name: 'Juan Raggi', count: 39, __typename: 'CountTuple' },
        { name: 'Roberto Arrieta', count: 39, __typename: 'CountTuple' },
        { name: 'Roberto Flores', count: 39, __typename: 'CountTuple' },
        { name: 'Oscar Ferrari', count: 39, __typename: 'CountTuple' },
        { name: 'Carlos Vidal', count: 38, __typename: 'CountTuple' },
        { name: 'Osvaldo Novarro', count: 37, __typename: 'CountTuple' },
        { name: 'Pedro Lauga', count: 37, __typename: 'CountTuple' },
        { name: 'Héctor De Rosas', count: 36, __typename: 'CountTuple' },
        { name: 'Alfredo Rojas', count: 36, __typename: 'CountTuple' },
        { name: 'Nina Miranda', count: 36, __typename: 'CountTuple' },
        { name: 'Carlos Galán', count: 35, __typename: 'CountTuple' },
        { name: 'Guillermo Rico', count: 35, __typename: 'CountTuple' },
        { name: 'Hugo Duval', count: 35, __typename: 'CountTuple' },
        { name: 'Antonio Maida', count: 34, __typename: 'CountTuple' },
        { name: 'Rubén Sánchez', count: 33, __typename: 'CountTuple' },
        { name: 'Lita Morales', count: 32, __typename: 'CountTuple' },
        { name: 'Ernesto Herrera', count: 32, __typename: 'CountTuple' },
        { name: 'Mario Alonso', count: 31, __typename: 'CountTuple' },
        { name: 'Roberto Videla', count: 31, __typename: 'CountTuple' },
        { name: 'Osvaldo Bazán', count: 31, __typename: 'CountTuple' },
        { name: 'Ángel Ramos', count: 31, __typename: 'CountTuple' },
        { name: 'Alberto Amor', count: 30, __typename: 'CountTuple' },
        { name: 'Sofia Bozán', count: 30, __typename: 'CountTuple' },
        { name: 'Jorge Rolando', count: 29, __typename: 'CountTuple' },
        { name: 'Ernesto Falcón', count: 29, __typename: 'CountTuple' },
        { name: 'Carlos Acuña', count: 29, __typename: 'CountTuple' },
        { name: 'Juan Carlos Rolón', count: 28, __typename: 'CountTuple' },
        { name: 'Omar Quiroz', count: 28, __typename: 'CountTuple' },
        { name: 'Romeo Gavioli', count: 28, __typename: 'CountTuple' },
        { name: 'Félix Gutiérrez', count: 28, __typename: 'CountTuple' },
        { name: 'Rodolfo Galé', count: 28, __typename: 'CountTuple' },
        { name: 'Tito Reyes', count: 28, __typename: 'CountTuple' },
        { name: 'Luis Correa', count: 28, __typename: 'CountTuple' },
        { name: 'Rosanna Falasca', count: 27, __typename: 'CountTuple' },
        { name: 'Héctor Farrel', count: 27, __typename: 'CountTuple' },
        { name: 'Lalo Martel', count: 27, __typename: 'CountTuple' },
        { name: 'Mercedes Carné', count: 27, __typename: 'CountTuple' },
        { name: 'Héctor Palacios', count: 26, __typename: 'CountTuple' },
        { name: 'Jorge Falcón', count: 26, __typename: 'CountTuple' },
        { name: 'Nelly Vázquez', count: 26, __typename: 'CountTuple' },
        { name: 'Aldo Calderón', count: 26, __typename: 'CountTuple' },
        { name: 'Oscar Macri', count: 25, __typename: 'CountTuple' },
        { name: 'Ricardo Herrera', count: 25, __typename: 'CountTuple' },
        { name: 'Carlos Galarce', count: 25, __typename: 'CountTuple' },
        { name: 'Alfredo del Río', count: 25, __typename: 'CountTuple' },
        { name: 'Carlos Almada', count: 25, __typename: 'CountTuple' },
        { name: 'Enzo Valentino', count: 24, __typename: 'CountTuple' },
        { name: 'Aldo Campoamor', count: 24, __typename: 'CountTuple' },
        { name: 'Tito Landó', count: 24, __typename: 'CountTuple' },
        { name: 'Adrián Guida', count: 24, __typename: 'CountTuple' },
        { name: 'Milva', count: 23, __typename: 'CountTuple' },
        { name: 'Enrique Lucero', count: 23, __typename: 'CountTuple' },
        { name: 'Domingo Conte', count: 23, __typename: 'CountTuple' },
        { name: 'Celia Gámez', count: 22, __typename: 'CountTuple' },
        { name: 'Adolfo Rivas', count: 22, __typename: 'CountTuple' },
        { name: 'Orlando Medina', count: 21, __typename: 'CountTuple' },
        { name: 'Hernán Salinas', count: 21, __typename: 'CountTuple' },
        { name: 'Julio Rodolfo', count: 20, __typename: 'CountTuple' },
        { name: 'Adriana Varela', count: 20, __typename: 'CountTuple' },
        { name: 'Tino García', count: 20, __typename: 'CountTuple' },
        { name: 'Ángel Cárdenas', count: 20, __typename: 'CountTuple' },
        { name: 'Armando Guerrico', count: 20, __typename: 'CountTuple' },
        { name: 'Oscar Alonso', count: 20, __typename: 'CountTuple' },
        { name: 'Juan Lauga', count: 19, __typename: 'CountTuple' },
        { name: 'Héctor Dario', count: 19, __typename: 'CountTuple' },
        { name: 'Gustavo Nocetti', count: 19, __typename: 'CountTuple' },
        { name: 'Fernando Soler', count: 19, __typename: 'CountTuple' },
        { name: 'Ricardo Olivera', count: 19, __typename: 'CountTuple' },
        { name: 'Ángel Díaz', count: 18, __typename: 'CountTuple' },
        { name: 'Eduardo Bianco', count: 18, __typename: 'CountTuple' },
        { name: 'Rodolfo Diaz', count: 18, __typename: 'CountTuple' },
        { name: 'Roberto Mancini', count: 18, __typename: 'CountTuple' },
        { name: 'Dorita Davis', count: 18, __typename: 'CountTuple' },
        { name: 'Emilia García', count: 18, __typename: 'CountTuple' },
        {
          name: 'Osvaldo Cruz Montenegro',
          count: 18,
          __typename: 'CountTuple',
        },
        { name: 'René Varela', count: 18, __typename: 'CountTuple' },
        { name: 'Jorge Ledesma', count: 18, __typename: 'CountTuple' },
        { name: 'Andrés Falgás', count: 17, __typename: 'CountTuple' },
        { name: 'Rosaura Silvestre', count: 17, __typename: 'CountTuple' },
        { name: 'Raúl Ledesma', count: 17, __typename: 'CountTuple' },
        { name: 'Alberto Diale', count: 17, __typename: 'CountTuple' },
        { name: 'Jaime Moreno', count: 17, __typename: 'CountTuple' },
        { name: 'Fernando Reyes', count: 17, __typename: 'CountTuple' },
        { name: 'Raúl Del Mar', count: 17, __typename: 'CountTuple' },
        { name: 'Orlando Verri', count: 17, __typename: 'CountTuple' },
        { name: 'Juan Carlos Miranda', count: 17, __typename: 'CountTuple' },
        { name: 'Maria De La Fuente', count: 17, __typename: 'CountTuple' },
        { name: 'Virginia Luque', count: 16, __typename: 'CountTuple' },
        { name: 'Alberto Reynal', count: 16, __typename: 'CountTuple' },
        { name: 'Carlos Nogués', count: 16, __typename: 'CountTuple' },
        { name: 'Piotr Rafałko', count: 16, __typename: 'CountTuple' },
        { name: 'Juan Carlos Casas', count: 16, __typename: 'CountTuple' },
        { name: 'Osvaldo Ribó', count: 16, __typename: 'CountTuple' },
        { name: 'Atahualpa Yupanqui', count: 16, __typename: 'CountTuple' },
        { name: 'Alberto Margal', count: 16, __typename: 'CountTuple' },
        { name: 'Carlos Aguirre', count: 15, __typename: 'CountTuple' },
        { name: 'Roberto Luque', count: 15, __typename: 'CountTuple' },
        { name: 'Susy Leiva', count: 15, __typename: 'CountTuple' },
        { name: 'Teresita Asprella', count: 15, __typename: 'CountTuple' },
        { name: 'Julián Centeya', count: 15, __typename: 'CountTuple' },
        { name: 'Alberto Casares', count: 15, __typename: 'CountTuple' },
        { name: 'Pedro Dátila', count: 15, __typename: 'CountTuple' },
        { name: 'Roberto Morel', count: 14, __typename: 'CountTuple' },
        { name: 'Isabel De Grana', count: 14, __typename: 'CountTuple' },
        { name: 'Pablo Moreno', count: 14, __typename: 'CountTuple' },
        { name: 'Horacio Quintana', count: 14, __typename: 'CountTuple' },
        { name: 'Claudio Bergé', count: 13, __typename: 'CountTuple' },
        { name: 'Horacio Roca', count: 13, __typename: 'CountTuple' },
        { name: 'Carlos Barbé', count: 12, __typename: 'CountTuple' },
        { name: 'Rodolfo Lemos', count: 12, __typename: 'CountTuple' },
        { name: 'Ignacio Murillo', count: 12, __typename: 'CountTuple' },
        { name: 'Carlos Barrios', count: 12, __typename: 'CountTuple' },
        { name: 'Enrique Dumas', count: 12, __typename: 'CountTuple' },
        { name: 'Lucho Gatica', count: 12, __typename: 'CountTuple' },
        { name: 'Horacio Casares', count: 12, __typename: 'CountTuple' },
        { name: 'Raúl Lavié', count: 12, __typename: 'CountTuple' },
        { name: 'Aida Denis', count: 12, __typename: 'CountTuple' },
        { name: 'Alberto Serna', count: 12, __typename: 'CountTuple' },
        { name: 'Héctor Alvarado', count: 12, __typename: 'CountTuple' },
        { name: 'Nestor Real', count: 12, __typename: 'CountTuple' },
        { name: 'Rafael Cisca', count: 11, __typename: 'CountTuple' },
        { name: 'Carlos Rossi', count: 11, __typename: 'CountTuple' },
        { name: 'Nelson Pino', count: 11, __typename: 'CountTuple' },
        { name: 'Hugo Marcel', count: 11, __typename: 'CountTuple' },
        { name: 'Juan Carlos Lamas', count: 11, __typename: 'CountTuple' },
        { name: 'Argentino Oliver', count: 11, __typename: 'CountTuple' },
        { name: 'Dante Ressia', count: 11, __typename: 'CountTuple' },
        { name: 'Carlos Almagro', count: 11, __typename: 'CountTuple' },
        { name: 'Rubén Juárez', count: 11, __typename: 'CountTuple' },
        { name: 'Hugo Soler', count: 11, __typename: 'CountTuple' },
        { name: 'Randona', count: 11, __typename: 'CountTuple' },
        { name: 'Carmen Duval', count: 11, __typename: 'CountTuple' },
        { name: 'Manuel Pizarro', count: 10, __typename: 'CountTuple' },
        { name: 'Jorge Cardozo', count: 10, __typename: 'CountTuple' },
        { name: 'Juan Carlos Thorry', count: 10, __typename: 'CountTuple' },
        { name: 'Alberto Hidalgo', count: 10, __typename: 'CountTuple' },
        { name: 'Walter Gutiérrez', count: 10, __typename: 'CountTuple' },
        { name: 'Armando Garrido', count: 10, __typename: 'CountTuple' },
        {
          name: 'Antonio Rodriguez Lesende',
          count: 10,
          __typename: 'CountTuple',
        },
        { name: 'Rubén Cané', count: 10, __typename: 'CountTuple' },
        { name: 'Antonella Ruggiero', count: 10, __typename: 'CountTuple' },
        { name: 'Roberto Taibo', count: 10, __typename: 'CountTuple' },
        { name: 'Ruben Peloni', count: 10, __typename: 'CountTuple' },
        { name: 'Alberto Cuello', count: 10, __typename: 'CountTuple' },
        { name: 'Jorge Sobral', count: 10, __typename: 'CountTuple' },
        { name: 'Juan Carlos Delson', count: 10, __typename: 'CountTuple' },
        { name: 'Julian Rosales', count: 10, __typename: 'CountTuple' },
        { name: 'Michiko Maeda', count: 10, __typename: 'CountTuple' },
        { name: 'Oscar Galán', count: 10, __typename: 'CountTuple' },
        { name: 'Rubén Maciel', count: 10, __typename: 'CountTuple' },
        { name: 'Dalva de Oliveira', count: 10, __typename: 'CountTuple' },
        { name: 'Genaro Veiga', count: 10, __typename: 'CountTuple' },
        { name: 'Carlos Montalvo', count: 9, __typename: 'CountTuple' },
        { name: 'Horacio Deval', count: 9, __typename: 'CountTuple' },
        { name: 'Santiago Devin', count: 9, __typename: 'CountTuple' },
        { name: 'Raúl Sanders', count: 9, __typename: 'CountTuple' },
        { name: 'Héctor Millán', count: 9, __typename: 'CountTuple' },
        { name: 'Carlos Bermúdez', count: 9, __typename: 'CountTuple' },
        { name: 'César Alberú', count: 9, __typename: 'CountTuple' },
        { name: 'Amadeo Mandarino', count: 9, __typename: 'CountTuple' },
        { name: 'Carlos Yanel', count: 9, __typename: 'CountTuple' },
        { name: 'Elba Berón', count: 8, __typename: 'CountTuple' },
        { name: 'Oscar Valeta', count: 8, __typename: 'CountTuple' },
        { name: 'Unspecified Female', count: 8, __typename: 'CountTuple' },
        { name: 'Elsa Rivas', count: 8, __typename: 'CountTuple' },
        { name: 'Carlos Heredia', count: 8, __typename: 'CountTuple' },
        { name: 'Alberto Santillán', count: 8, __typename: 'CountTuple' },
        { name: 'Olga Lamas', count: 8, __typename: 'CountTuple' },
        { name: 'Tani Zerja', count: 8, __typename: 'CountTuple' },
        { name: 'Alberto Guzmán', count: 8, __typename: 'CountTuple' },
        { name: 'Rafael Canaro', count: 8, __typename: 'CountTuple' },
        { name: 'José E. Galarza', count: 8, __typename: 'CountTuple' },
        { name: 'Roberto Decarre', count: 8, __typename: 'CountTuple' },
        { name: 'Osvaldo Moreno', count: 8, __typename: 'CountTuple' },
        { name: 'Carlos Mayel', count: 8, __typename: 'CountTuple' },
        { name: 'Ramón Regueira', count: 8, __typename: 'CountTuple' },
        { name: 'Olga Delgrossi', count: 8, __typename: 'CountTuple' },
        { name: 'Osvaldo Cordó', count: 8, __typename: 'CountTuple' },
        { name: 'Héctor Coral', count: 7, __typename: 'CountTuple' },
        { name: 'Luis Tolosa', count: 7, __typename: 'CountTuple' },
        { name: 'Tito Schipa', count: 7, __typename: 'CountTuple' },
        {
          name: 'Alberto Hilarion Acuña',
          count: 7,
          __typename: 'CountTuple',
        },
        { name: 'Héctor Insúa', count: 7, __typename: 'CountTuple' },
        { name: 'Carlos Saavedra', count: 7, __typename: 'CountTuple' },
        { name: 'Ortega del Cerro', count: 7, __typename: 'CountTuple' },
        { name: 'Horacio Pettorossi', count: 7, __typename: 'CountTuple' },
        { name: 'Ruth Durante', count: 7, __typename: 'CountTuple' },
        { name: 'Juan Carlos Cobos', count: 7, __typename: 'CountTuple' },
        { name: 'Carmen Del Moral', count: 7, __typename: 'CountTuple' },
        { name: 'Victoria Díaz', count: 7, __typename: 'CountTuple' },
        { name: 'Alberto Radamés', count: 7, __typename: 'CountTuple' },
        { name: 'Rubén Grillo', count: 7, __typename: 'CountTuple' },
        { name: 'Diego Solís', count: 7, __typename: 'CountTuple' },
        { name: 'Roberto Lemos', count: 7, __typename: 'CountTuple' },
        { name: 'Marcelo Paz', count: 7, __typename: 'CountTuple' },
        { name: 'Elsa Moreno', count: 7, __typename: 'CountTuple' },
        { name: 'Julia Vidal', count: 7, __typename: 'CountTuple' },
        { name: 'Julio Fontana', count: 6, __typename: 'CountTuple' },
        { name: 'Sergio Gobi', count: 6, __typename: 'CountTuple' },
        { name: 'Alberto Larena', count: 6, __typename: 'CountTuple' },
        { name: 'Carlos Casado', count: 6, __typename: 'CountTuple' },
        { name: 'Diana Duran', count: 6, __typename: 'CountTuple' },
        { name: 'Isabel de Angelis', count: 6, __typename: 'CountTuple' },
        { name: 'Alberto Aguirre', count: 6, __typename: 'CountTuple' },
        { name: 'Raúl Aldao', count: 6, __typename: 'CountTuple' },
        { name: 'Agustín Volpe', count: 6, __typename: 'CountTuple' },
        { name: 'Jorge Linares', count: 6, __typename: 'CountTuple' },
        { name: 'Alberto Fontán Luna', count: 6, __typename: 'CountTuple' },
        { name: 'Héctor Gagliardi', count: 6, __typename: 'CountTuple' },
        { name: 'Marcelo Peña', count: 6, __typename: 'CountTuple' },
        { name: 'Jorge Garré', count: 6, __typename: 'CountTuple' },
        { name: 'Alberto Carol', count: 6, __typename: 'CountTuple' },
        { name: 'Andrés Peyró', count: 6, __typename: 'CountTuple' },
        { name: 'Omar Carranza', count: 6, __typename: 'CountTuple' },
        { name: 'Néstor Rodi', count: 6, __typename: 'CountTuple' },
        { name: 'Chola Luna', count: 5, __typename: 'CountTuple' },
        { name: 'Francisco Canaro', count: 5, __typename: 'CountTuple' },
        { name: 'Rubén Linares', count: 5, __typename: 'CountTuple' },
        { name: 'Nicolas Gianastacio', count: 5, __typename: 'CountTuple' },
        { name: 'Carmen Idal', count: 5, __typename: 'CountTuple' },
        { name: 'Walter Laborde', count: 5, __typename: 'CountTuple' },
        { name: 'Alberto Lago', count: 5, __typename: 'CountTuple' },
        {
          name: 'Luis Esteban Mandarino',
          count: 5,
          __typename: 'CountTuple',
        },
        { name: 'Martín Podestá', count: 5, __typename: 'CountTuple' },
        { name: 'Amanda Ledesma', count: 5, __typename: 'CountTuple' },
        { name: 'Jorge De La Peña', count: 5, __typename: 'CountTuple' },
        { name: 'Alfredo Montalbán', count: 5, __typename: 'CountTuple' },
        { name: 'Carlos Bares', count: 5, __typename: 'CountTuple' },
        { name: 'Roberto Cortés', count: 5, __typename: 'CountTuple' },
        { name: 'Roberto Yanés', count: 5, __typename: 'CountTuple' },
        { name: 'Oscar Peralta', count: 5, __typename: 'CountTuple' },
        { name: 'Chito Faró', count: 5, __typename: 'CountTuple' },
        { name: 'Luis Roca', count: 5, __typename: 'CountTuple' },
        { name: 'Joaquina Carreras', count: 5, __typename: 'CountTuple' },
        { name: 'Claudia Lucero', count: 5, __typename: 'CountTuple' },
        { name: 'Osvaldo Arana', count: 5, __typename: 'CountTuple' },
        { name: 'Roberto Caló', count: 4, __typename: 'CountTuple' },
        { name: 'Bachicha', count: 4, __typename: 'CountTuple' },
        { name: 'Oscar Nelson', count: 4, __typename: 'CountTuple' },
        { name: 'Marcelo Biondini', count: 4, __typename: 'CountTuple' },
        { name: 'Luis Mariano', count: 4, __typename: 'CountTuple' },
        { name: 'Carlos Boledi', count: 4, __typename: 'CountTuple' },
        { name: 'Mario Melfi', count: 4, __typename: 'CountTuple' },
        { name: 'Héctor Juncal', count: 4, __typename: 'CountTuple' },
        { name: 'Oscar Luna', count: 4, __typename: 'CountTuple' },
        { name: 'Jorge Beiró', count: 4, __typename: 'CountTuple' },
        { name: 'Juan Carlos Fabri', count: 4, __typename: 'CountTuple' },
        { name: 'Mario Luna', count: 4, __typename: 'CountTuple' },
        { name: 'Mario Beltrán', count: 4, __typename: 'CountTuple' },
        { name: 'Jorge Hidalgo', count: 4, __typename: 'CountTuple' },
        { name: 'Osvaldo Chazarreta', count: 4, __typename: 'CountTuple' },
        { name: 'Alberto Morel', count: 4, __typename: 'CountTuple' },
        { name: 'Roberto Quiroga', count: 4, __typename: 'CountTuple' },
        { name: 'Alfredo Dalton', count: 4, __typename: 'CountTuple' },
        { name: 'Gloria Diaz', count: 4, __typename: 'CountTuple' },
        { name: 'Roberto Alvar', count: 4, __typename: 'CountTuple' },
        { name: 'Walter Cabral', count: 4, __typename: 'CountTuple' },
        { name: 'Pablo Lozano', count: 4, __typename: 'CountTuple' },
        { name: 'Luis Alberto Fleitas', count: 4, __typename: 'CountTuple' },
        { name: 'Roberto Medina', count: 4, __typename: 'CountTuple' },
        { name: 'Roberto Ángel Baiot', count: 4, __typename: 'CountTuple' },
        { name: 'Andrés Galarce', count: 4, __typename: 'CountTuple' },
        { name: 'Pietro Sinigaglia', count: 4, __typename: 'CountTuple' },
        {
          name: 'Juan Carlos Marambio Catán',
          count: 4,
          __typename: 'CountTuple',
        },
        { name: 'Mario Visconti', count: 4, __typename: 'CountTuple' },
        { name: 'Alfredo de la Colina', count: 4, __typename: 'CountTuple' },
        { name: 'Víctor Ruiz', count: 4, __typename: 'CountTuple' },
        { name: 'Hugo Roca', count: 4, __typename: 'CountTuple' },
        { name: 'Julio Silva Salinas', count: 4, __typename: 'CountTuple' },
        { name: 'Néstor Peña', count: 4, __typename: 'CountTuple' },
        { name: 'Carlos Persi', count: 4, __typename: 'CountTuple' },
        { name: 'Carlos Valdéz', count: 4, __typename: 'CountTuple' },
        { name: 'Ricardo Blanco', count: 4, __typename: 'CountTuple' },
        { name: 'Dinah Lang', count: 4, __typename: 'CountTuple' },
        { name: 'José Bohr', count: 4, __typename: 'CountTuple' },
        { name: 'Ángel Varela', count: 4, __typename: 'CountTuple' },
        { name: 'Rosita Montemar', count: 3, __typename: 'CountTuple' },
        { name: 'Guy Berry', count: 3, __typename: 'CountTuple' },
        { name: 'Sabina Olmos', count: 3, __typename: 'CountTuple' },
        { name: 'Blanca Mooney', count: 3, __typename: 'CountTuple' },
        { name: 'Alfredo Castells', count: 3, __typename: 'CountTuple' },
        { name: 'Fernando Raymond', count: 3, __typename: 'CountTuple' },
        { name: 'Enrique Forte', count: 3, __typename: 'CountTuple' },
        { name: 'Roman Prince', count: 3, __typename: 'CountTuple' },
        { name: 'José Duarte', count: 3, __typename: 'CountTuple' },
        { name: 'Alberto Tagle', count: 3, __typename: 'CountTuple' },
        { name: 'Diego Hernan', count: 3, __typename: 'CountTuple' },
        { name: 'Raúl Lavalle', count: 3, __typename: 'CountTuple' },
        { name: 'Mieczysław Fogg', count: 3, __typename: 'CountTuple' },
        { name: 'Néstor Fabián', count: 3, __typename: 'CountTuple' },
        { name: 'Raúl Angelo', count: 3, __typename: 'CountTuple' },
        { name: 'Mariano Balcarce', count: 3, __typename: 'CountTuple' },
        { name: 'Juana Larrauri', count: 3, __typename: 'CountTuple' },
        { name: 'Patrocinio Díaz', count: 3, __typename: 'CountTuple' },
        { name: 'Eugenio Viñas', count: 3, __typename: 'CountTuple' },
        { name: 'Carlos Guido', count: 3, __typename: 'CountTuple' },
        { name: 'Nilda Wilson', count: 3, __typename: 'CountTuple' },
        { name: 'Carlos Casares', count: 3, __typename: 'CountTuple' },
        { name: 'Anita Palmero', count: 3, __typename: 'CountTuple' },
        { name: 'Carlos Del Monte', count: 3, __typename: 'CountTuple' },
        { name: 'José Berón', count: 3, __typename: 'CountTuple' },
        { name: 'Ricardo Argentino', count: 3, __typename: 'CountTuple' },
        { name: 'Ernesto Rondó', count: 3, __typename: 'CountTuple' },
        { name: 'Daniel Adamo', count: 3, __typename: 'CountTuple' },
        { name: 'Pedro De Luca', count: 3, __typename: 'CountTuple' },
        { name: 'Virginia Doris', count: 3, __typename: 'CountTuple' },
        { name: 'Pedro Vargas', count: 3, __typename: 'CountTuple' },
        { name: 'Osvaldo Barbé', count: 3, __typename: 'CountTuple' },
        { name: 'Raúl Quiroz', count: 3, __typename: 'CountTuple' },
        { name: 'Ricardo Duarte', count: 3, __typename: 'CountTuple' },
        { name: 'Daniel Cortés', count: 3, __typename: 'CountTuple' },
        { name: 'Enalmar de María', count: 3, __typename: 'CountTuple' },
        { name: 'Gloria Vélez', count: 2, __typename: 'CountTuple' },
        { name: 'Carlos Budini', count: 2, __typename: 'CountTuple' },
        { name: 'Héctor Acosta', count: 2, __typename: 'CountTuple' },
        { name: 'Cerry Brian', count: 2, __typename: 'CountTuple' },
        { name: 'Antonio Prieto', count: 2, __typename: 'CountTuple' },
        { name: 'Oscar Gallardo', count: 2, __typename: 'CountTuple' },
        { name: 'Jorge Torres', count: 2, __typename: 'CountTuple' },
        { name: 'Ricardo Cortez', count: 2, __typename: 'CountTuple' },
        { name: 'Carlos Burgos', count: 2, __typename: 'CountTuple' },
        { name: 'José B. Sánchez', count: 2, __typename: 'CountTuple' },
        { name: 'Osvaldo Pugliese', count: 2, __typename: 'CountTuple' },
        { name: 'Jorge Denis', count: 2, __typename: 'CountTuple' },
        { name: 'Raúl Garcés', count: 2, __typename: 'CountTuple' },
        { name: 'Carlos Malbrán', count: 2, __typename: 'CountTuple' },
        { name: 'Roberto Solar', count: 2, __typename: 'CountTuple' },
        { name: 'Vicente Crisera', count: 2, __typename: 'CountTuple' },
        { name: 'Jorge Guillermo', count: 2, __typename: 'CountTuple' },
        {
          name: "Raúl Cobián 'Tanguito'",
          count: 2,
          __typename: 'CountTuple',
        },
        { name: 'Raúl Laborde', count: 2, __typename: 'CountTuple' },
        { name: 'Julia De Alba', count: 2, __typename: 'CountTuple' },
        { name: 'Susy del Carril', count: 2, __typename: 'CountTuple' },
        { name: 'Roberto Beltrán', count: 2, __typename: 'CountTuple' },
        { name: 'Roberto Basso', count: 2, __typename: 'CountTuple' },
        { name: 'Carlos Ferrán', count: 2, __typename: 'CountTuple' },
        { name: 'Mario Lagos', count: 2, __typename: 'CountTuple' },
        { name: 'Carlos Olmedo', count: 2, __typename: 'CountTuple' },
        { name: 'Héctor Omar', count: 2, __typename: 'CountTuple' },
        { name: 'Roberto Campos', count: 2, __typename: 'CountTuple' },
        { name: 'Reynaldo Martín', count: 2, __typename: 'CountTuple' },
        { name: 'Mario Ponce De Leon', count: 2, __typename: 'CountTuple' },
        { name: 'Beatriz Maselli', count: 2, __typename: 'CountTuple' },
        { name: 'Fontán Reyes', count: 2, __typename: 'CountTuple' },
        { name: 'Alberto Rial', count: 2, __typename: 'CountTuple' },
        { name: 'Oscar Ugarte', count: 2, __typename: 'CountTuple' },
        { name: 'Enrique Carbel', count: 2, __typename: 'CountTuple' },
        { name: 'Osvaldo Morel', count: 2, __typename: 'CountTuple' },
        { name: 'Elsa Morán', count: 2, __typename: 'CountTuple' },
        {
          name: "Luis 'Cucaracha' Zinkes",
          count: 2,
          __typename: 'CountTuple',
        },
        { name: 'Roberto Echagüe', count: 2, __typename: 'CountTuple' },
        { name: 'Elena Medrano', count: 2, __typename: 'CountTuple' },
        { name: 'Alberto Del Campo', count: 2, __typename: 'CountTuple' },
        { name: 'Ricardo Aguilar', count: 2, __typename: 'CountTuple' },
        { name: 'Mirna Mores', count: 2, __typename: 'CountTuple' },
        { name: 'Lito Bayardo', count: 2, __typename: 'CountTuple' },
        { name: 'Bob Toledo', count: 2, __typename: 'CountTuple' },
        { name: 'Roberto Abrodos', count: 2, __typename: 'CountTuple' },
        { name: 'Ricardo Farias', count: 2, __typename: 'CountTuple' },
        { name: 'Ricardo Medina', count: 2, __typename: 'CountTuple' },
        { name: 'Héctor Montes', count: 2, __typename: 'CountTuple' },
        { name: 'Carlos Ortega', count: 2, __typename: 'CountTuple' },
        { name: 'José Balbi', count: 2, __typename: 'CountTuple' },
        { name: 'Amadeo Lomio', count: 2, __typename: 'CountTuple' },
        { name: 'Héctor Beltrán', count: 2, __typename: 'CountTuple' },
        { name: 'Nito Mores', count: 2, __typename: 'CountTuple' },
        { name: 'Tita Galatro', count: 2, __typename: 'CountTuple' },
        { name: 'Mercedes Serrano', count: 2, __typename: 'CountTuple' },
        { name: 'Chola Bosch', count: 2, __typename: 'CountTuple' },
        { name: 'Raúl Figueroa', count: 2, __typename: 'CountTuple' },
        { name: 'Alfredo E. Gobbi', count: 2, __typename: 'CountTuple' },
        { name: 'Roberto Morales', count: 2, __typename: 'CountTuple' },
        { name: 'Carlos Maidana', count: 2, __typename: 'CountTuple' },
        { name: 'Francisco Lomuto', count: 1, __typename: 'CountTuple' },
        { name: 'Carlos Di Sarli', count: 1, __typename: 'CountTuple' },
        { name: 'Guillermo Galvé', count: 1, __typename: 'CountTuple' },
        { name: 'Daniel Melingo', count: 1, __typename: 'CountTuple' },
        { name: 'Lidia Desmond', count: 1, __typename: 'CountTuple' },
        { name: 'Jorge Nasser', count: 1, __typename: 'CountTuple' },
        { name: 'Pilar Arcos', count: 1, __typename: 'CountTuple' },
        { name: 'Linda Thelma', count: 1, __typename: 'CountTuple' },
        { name: 'Zulema Robles', count: 1, __typename: 'CountTuple' },
        { name: 'Federico Linae', count: 1, __typename: 'CountTuple' },
        { name: 'Hugo Gutiérrez', count: 1, __typename: 'CountTuple' },
        { name: 'Luis Omar Zunino', count: 1, __typename: 'CountTuple' },
        { name: 'Carlos Bernal', count: 1, __typename: 'CountTuple' },
        { name: 'Paloma Efron', count: 1, __typename: 'CountTuple' },
        { name: 'Juan Giliberti', count: 1, __typename: 'CountTuple' },
        { name: 'German Darrien', count: 1, __typename: 'CountTuple' },
        { name: 'Susana Moreno', count: 1, __typename: 'CountTuple' },
        { name: 'Italo Goyeche', count: 1, __typename: 'CountTuple' },
        { name: 'Adam Aston', count: 1, __typename: 'CountTuple' },
        { name: 'Héctor Maciel', count: 1, __typename: 'CountTuple' },
        { name: 'Mario Cané', count: 1, __typename: 'CountTuple' },
        { name: 'Dante Rossi', count: 1, __typename: 'CountTuple' },
        { name: 'Adalberto Perazo', count: 1, __typename: 'CountTuple' },
        { name: 'Aída Luz', count: 1, __typename: 'CountTuple' },
        { name: 'Carlos Ignacio Rivero', count: 1, __typename: 'CountTuple' },
        { name: 'Rita Marín', count: 1, __typename: 'CountTuple' },
        { name: 'Raquel Notar', count: 1, __typename: 'CountTuple' },
        { name: 'Mariano Mores', count: 1, __typename: 'CountTuple' },
        { name: 'Amanda Vidal', count: 1, __typename: 'CountTuple' },
        { name: 'Jorge Rubino', count: 1, __typename: 'CountTuple' },
        { name: 'Iván Casadó', count: 1, __typename: 'CountTuple' },
        { name: 'Silvia Lallana', count: 1, __typename: 'CountTuple' },
        { name: 'Manlio Francia', count: 1, __typename: 'CountTuple' },
        { name: 'Déo Costa', count: 1, __typename: 'CountTuple' },
        { name: 'Laura Torres', count: 1, __typename: 'CountTuple' },
        { name: 'Samuel Aguayo', count: 1, __typename: 'CountTuple' },
        { name: 'Pedro Beramendi', count: 1, __typename: 'CountTuple' },
        { name: 'Eladia Blázquez', count: 1, __typename: 'CountTuple' },
        { name: 'Adhelma Falcón', count: 1, __typename: 'CountTuple' },
        { name: 'Héctor Castel', count: 1, __typename: 'CountTuple' },
        { name: 'Carmelita Aubert', count: 1, __typename: 'CountTuple' },
        { name: 'Aníbal Troilo', count: 1, __typename: 'CountTuple' },
        { name: 'Fanny Navarro', count: 1, __typename: 'CountTuple' },
        { name: 'Armando Arolas', count: 1, __typename: 'CountTuple' },
        { name: 'Lidia Borda', count: 1, __typename: 'CountTuple' },
        { name: 'Silvia Del Rio', count: 1, __typename: 'CountTuple' },
        { name: 'Hugo Del Valle', count: 1, __typename: 'CountTuple' },
        { name: 'María Teresa Greco', count: 1, __typename: 'CountTuple' },
        { name: "Mario D'Elía", count: 1, __typename: 'CountTuple' },
        { name: 'Marcel Verán', count: 1, __typename: 'CountTuple' },
        { name: 'Elena Lauri', count: 1, __typename: 'CountTuple' },
        { name: 'Adolfo Berta', count: 1, __typename: 'CountTuple' },
        { name: 'Francisco Spaventa', count: 1, __typename: 'CountTuple' },
        { name: 'Paula Gales', count: 1, __typename: 'CountTuple' },
        { name: 'Horacio Susena', count: 1, __typename: 'CountTuple' },
        { name: 'Sergio Cansino', count: 1, __typename: 'CountTuple' },
        { name: 'Carlos Solari', count: 1, __typename: 'CountTuple' },
        { name: 'Cholo Aguirre', count: 1, __typename: 'CountTuple' },
        { name: 'María Graña', count: 1, __typename: 'CountTuple' },
        { name: 'Rosa Berón', count: 1, __typename: 'CountTuple' },
        { name: 'Alberto Fuentes', count: 1, __typename: 'CountTuple' },
        { name: 'Amelita Baltar', count: 1, __typename: 'CountTuple' },
        { name: 'Juan Llossas', count: 1, __typename: 'CountTuple' },
        { name: 'Eduardo Espinoza', count: 1, __typename: 'CountTuple' },
        { name: 'Patricia Lasala', count: 1, __typename: 'CountTuple' },
        { name: 'Virginia Vera', count: 1, __typename: 'CountTuple' },
        { name: 'Ignacio Díaz', count: 1, __typename: 'CountTuple' },
        { name: 'Mario Córdoba', count: 1, __typename: 'CountTuple' },
        { name: 'Roberto Deirene', count: 1, __typename: 'CountTuple' },
        { name: 'Lely Morel', count: 1, __typename: 'CountTuple' },
        { name: 'Anita Mendy', count: 1, __typename: 'CountTuple' },
        { name: 'Félix Picherna', count: 1, __typename: 'CountTuple' },
        { name: 'Dorita Zárate', count: 1, __typename: 'CountTuple' },
        { name: 'Carlos Gari', count: 1, __typename: 'CountTuple' },
        { name: 'Tino Rossi', count: 1, __typename: 'CountTuple' },
        { name: 'José Ángel Trelles', count: 1, __typename: 'CountTuple' },
      ],
      orchestra: [
        { name: 'Francisco Canaro', count: 2826, __typename: 'CountTuple' },
        { name: 'Unknown', count: 1923, __typename: 'CountTuple' },
        { name: 'Roberto Firpo', count: 1292, __typename: 'CountTuple' },
        { name: 'Osvaldo Fresedo', count: 1040, __typename: 'CountTuple' },
        { name: "Juan D'Arienzo", count: 1034, __typename: 'CountTuple' },
        { name: 'Guitarra', count: 815, __typename: 'CountTuple' },
        { name: 'Guillermo Barbieri', count: 732, __typename: 'CountTuple' },
        { name: 'Francisco Lomuto', count: 687, __typename: 'CountTuple' },
        { name: 'José Ricardo', count: 580, __typename: 'CountTuple' },
        { name: 'Aníbal Troilo', count: 538, __typename: 'CountTuple' },
        { name: 'Osvaldo Pugliese', count: 532, __typename: 'CountTuple' },
        { name: 'Edgardo Donato', count: 518, __typename: 'CountTuple' },
        { name: 'Julio De Caro', count: 492, __typename: 'CountTuple' },
        {
          name: 'Orquesta Típica Victor',
          count: 492,
          __typename: 'CountTuple',
        },
        { name: 'Alfredo De Angelis', count: 447, __typename: 'CountTuple' },
        { name: 'Carlos Di Sarli', count: 438, __typename: 'CountTuple' },
        { name: 'Héctor Varela', count: 423, __typename: 'CountTuple' },
        { name: 'Miguel Caló', count: 409, __typename: 'CountTuple' },
        { name: 'Armando Pontier', count: 394, __typename: 'CountTuple' },
        { name: 'Enrique Rodríguez', count: 382, __typename: 'CountTuple' },
        { name: 'Juan Félix Maglio', count: 347, __typename: 'CountTuple' },
        { name: 'José Basso', count: 286, __typename: 'CountTuple' },
        { name: 'Florindo Sassone', count: 247, __typename: 'CountTuple' },
        { name: 'José María Aguilar', count: 241, __typename: 'CountTuple' },
        { name: 'Astor Piazzolla', count: 215, __typename: 'CountTuple' },
        { name: 'Pedro Maffia', count: 209, __typename: 'CountTuple' },
        {
          name: 'dir. Francisco Canaro',
          count: 204,
          __typename: 'CountTuple',
        },
        { name: 'Adolfo Carabelli', count: 194, __typename: 'CountTuple' },
        { name: 'Rodolfo Biagi', count: 187, __typename: 'CountTuple' },
        { name: 'Eduardo Bianco', count: 185, __typename: 'CountTuple' },
        { name: 'Ricardo Tanturi', count: 183, __typename: 'CountTuple' },
        { name: 'Domingo Federico', count: 171, __typename: 'CountTuple' },
        { name: 'Bachicha', count: 166, __typename: 'CountTuple' },
        { name: 'Enrique Francini', count: 158, __typename: 'CountTuple' },
        { name: 'Lucio Demare', count: 155, __typename: 'CountTuple' },
        {
          name: 'Ángel Domingo Riverol',
          count: 148,
          __typename: 'CountTuple',
        },
        { name: "Ángel D'Agostino", count: 146, __typename: 'CountTuple' },
        { name: 'Fulvio Salamanca', count: 145, __typename: 'CountTuple' },
        { name: 'Quinteto Pirincho', count: 126, __typename: 'CountTuple' },
        { name: 'Rafael Canaro', count: 117, __typename: 'CountTuple' },
        { name: 'Pedro Laurenz', count: 108, __typename: 'CountTuple' },
        { name: 'Ciriaco Ortiz', count: 102, __typename: 'CountTuple' },
        { name: 'Horacio Salgán', count: 99, __typename: 'CountTuple' },
        { name: 'Juan Sánchez Gorio', count: 97, __typename: 'CountTuple' },
        { name: 'Roberto Zerrillo', count: 96, __typename: 'CountTuple' },
        { name: 'Ensemble Hyperion', count: 95, __typename: 'CountTuple' },
        { name: 'Ángel F. Condercuri', count: 93, __typename: 'CountTuple' },
        {
          name: 'Orquesta Típica Porteña',
          count: 92,
          __typename: 'CountTuple',
        },
        { name: 'Juan Bautista Guido', count: 86, __typename: 'CountTuple' },
        { name: 'Enrique Delfino', count: 85, __typename: 'CountTuple' },
        { name: 'Alfredo J. Gobbi', count: 83, __typename: 'CountTuple' },
        { name: 'Leopoldo Federico', count: 82, __typename: 'CountTuple' },
        { name: 'Quinteto Don Pancho', count: 81, __typename: 'CountTuple' },
        { name: 'Juan Carlos Cobián', count: 79, __typename: 'CountTuple' },
        { name: 'Miguel Villasboas', count: 78, __typename: 'CountTuple' },
        { name: 'Manuel Pizarro', count: 76, __typename: 'CountTuple' },
        { name: 'Francisco Rotundo', count: 76, __typename: 'CountTuple' },
        {
          name: 'Ricardo Luis Brignolo',
          count: 75,
          __typename: 'CountTuple',
        },
        { name: 'Color Tango', count: 72, __typename: 'CountTuple' },
        { name: 'Osmar Maderna', count: 69, __typename: 'CountTuple' },
        { name: 'Juan Cambareri', count: 67, __typename: 'CountTuple' },
        {
          name: 'Orquesta Típica Tokio',
          count: 66,
          __typename: 'CountTuple',
        },
        { name: 'QuinTango', count: 65, __typename: 'CountTuple' },
        { name: 'Osvaldo Requena', count: 64, __typename: 'CountTuple' },
        {
          name: 'Orquesta Victor popular',
          count: 63,
          __typename: 'CountTuple',
        },
        { name: 'Domingo Julio Vivas', count: 63, __typename: 'CountTuple' },
        { name: 'Hugo Díaz', count: 63, __typename: 'CountTuple' },
        { name: 'Enrique Mora', count: 63, __typename: 'CountTuple' },
        { name: 'Eduardo Del Piano', count: 62, __typename: 'CountTuple' },
        { name: 'Roberto Caló', count: 62, __typename: 'CountTuple' },
        { name: 'Francisco Pracánico', count: 61, __typename: 'CountTuple' },
        { name: 'Luis Petrucelli', count: 61, __typename: 'CountTuple' },
        { name: 'Donato Racciatti', count: 61, __typename: 'CountTuple' },
        { name: 'Horacio Pettorossi', count: 60, __typename: 'CountTuple' },
        { name: 'Quinteto Ángel', count: 59, __typename: 'CountTuple' },
        { name: 'Enrique Alessio', count: 56, __typename: 'CountTuple' },
        { name: 'Carlos Figari', count: 54, __typename: 'CountTuple' },
        { name: 'Argentino Galván', count: 52, __typename: 'CountTuple' },
        { name: 'Adolfo Pérez', count: 51, __typename: 'CountTuple' },
        { name: 'Típica Select', count: 51, __typename: 'CountTuple' },
        { name: 'Alberto Castellano', count: 51, __typename: 'CountTuple' },
        { name: 'Mariano Mores', count: 51, __typename: 'CountTuple' },
        { name: 'Armando Lacava', count: 49, __typename: 'CountTuple' },
        { name: 'Juan Canaro', count: 46, __typename: 'CountTuple' },
        { name: 'José Bohr', count: 46, __typename: 'CountTuple' },
        { name: 'Minotti Di Cicco', count: 45, __typename: 'CountTuple' },
        { name: 'José Canet', count: 45, __typename: 'CountTuple' },
        { name: 'Roberto Grela', count: 44, __typename: 'CountTuple' },
        { name: 'Anselmo A. Aieta', count: 43, __typename: 'CountTuple' },
        { name: 'Genaro Espósito', count: 42, __typename: 'CountTuple' },
        { name: 'Trío Argentino', count: 42, __typename: 'CountTuple' },
        { name: 'Alberto Mancione', count: 41, __typename: 'CountTuple' },
        { name: 'José García', count: 41, __typename: 'CountTuple' },
        { name: 'José Servidio', count: 39, __typename: 'CountTuple' },
        { name: 'Emilio Brameri', count: 39, __typename: 'CountTuple' },
        {
          name: 'Cuarteto típico Los ases',
          count: 39,
          __typename: 'CountTuple',
        },
        { name: 'Carlos García', count: 38, __typename: 'CountTuple' },
        { name: 'Antonio Bonavena', count: 38, __typename: 'CountTuple' },
        { name: 'Manuel Parada', count: 38, __typename: 'CountTuple' },
        { name: 'Armando Cupo', count: 37, __typename: 'CountTuple' },
        { name: 'Joaquín Do Reyes', count: 37, __typename: 'CountTuple' },
        { name: 'Emilio Balcarce', count: 36, __typename: 'CountTuple' },
        { name: 'Raúl Miguel Garello', count: 35, __typename: 'CountTuple' },
        {
          name: 'Los señores del tango',
          count: 34,
          __typename: 'CountTuple',
        },
        { name: 'Mario Maurano', count: 34, __typename: 'CountTuple' },
        { name: 'Agesilao Ferrazzano', count: 33, __typename: 'CountTuple' },
        { name: 'Cayetano Puglisi', count: 33, __typename: 'CountTuple' },
        { name: 'Eduardo Arolas', count: 31, __typename: 'CountTuple' },
        { name: 'Ricardo Malerba', count: 31, __typename: 'CountTuple' },
        { name: 'Osvaldo Manzi', count: 29, __typename: 'CountTuple' },
        {
          name: 'Alberto Oscar Gentile',
          count: 29,
          __typename: 'CountTuple',
        },
        { name: 'Alfredo Malerba', count: 28, __typename: 'CountTuple' },
        {
          name: 'Los muchachos de antes',
          count: 28,
          __typename: 'CountTuple',
        },
        { name: 'A. J. Pesenti', count: 28, __typename: 'CountTuple' },
        { name: 'Jorge Dragone', count: 28, __typename: 'CountTuple' },
        { name: 'Jorge Caldara', count: 28, __typename: 'CountTuple' },
        { name: 'Gabriel Clausi', count: 27, __typename: 'CountTuple' },
        { name: 'Francisco Lauro', count: 27, __typename: 'CountTuple' },
        { name: 'Alberto Di Paulo', count: 27, __typename: 'CountTuple' },
        {
          name: 'Juan de Dios Filiberto',
          count: 27,
          __typename: 'CountTuple',
        },
        { name: 'Terig Tucci', count: 26, __typename: 'CountTuple' },
        {
          name: 'Orquesta Típica Corrientes',
          count: 26,
          __typename: 'CountTuple',
        },
        { name: 'Antonio Rodio', count: 26, __typename: 'CountTuple' },
        { name: 'Trio Neuklang', count: 26, __typename: 'CountTuple' },
        { name: 'Mario Demarco', count: 26, __typename: 'CountTuple' },
        {
          name: "Los Solistas de D'Arienzo",
          count: 25,
          __typename: 'CountTuple',
        },
        { name: 'Héctor María Artola', count: 25, __typename: 'CountTuple' },
        { name: 'Los Provincianos', count: 24, __typename: 'CountTuple' },
        { name: 'Feliciano Brunelli', count: 24, __typename: 'CountTuple' },
        { name: 'Xavier Cugat', count: 24, __typename: 'CountTuple' },
        { name: 'Mario Canaro', count: 24, __typename: 'CountTuple' },
        { name: 'Vicente Greco', count: 24, __typename: 'CountTuple' },
        { name: 'Cristóbal Herreros', count: 24, __typename: 'CountTuple' },
        { name: 'Ernesto Baffa', count: 24, __typename: 'CountTuple' },
        { name: 'Lorenzo Barbero', count: 23, __typename: 'CountTuple' },
        { name: 'Héctor Stamponi', count: 23, __typename: 'CountTuple' },
        { name: 'Julio Pollero', count: 23, __typename: 'CountTuple' },
        {
          name: 'Cuarteto Troilo-Grela',
          count: 23,
          __typename: 'CountTuple',
        },
        {
          name: 'Ubaldo Aquiles De Lio',
          count: 23,
          __typename: 'CountTuple',
        },
        {
          name: 'Orquesta Típica Brodman-Alfaro',
          count: 23,
          __typename: 'CountTuple',
        },
        { name: 'Osvaldo Berlingieri', count: 22, __typename: 'CountTuple' },
        { name: 'Alfredo Attadía', count: 22, __typename: 'CountTuple' },
        { name: 'Luis Stazo', count: 21, __typename: 'CountTuple' },
        { name: 'Graciano Gómez', count: 21, __typename: 'CountTuple' },
        { name: 'Los siete del tango', count: 20, __typename: 'CountTuple' },
        { name: 'Manuel Buzón', count: 20, __typename: 'CountTuple' },
        {
          name: 'Orquesta Puglia-Pedroza',
          count: 19,
          __typename: 'CountTuple',
        },
        { name: 'Octeto Buenos Aires', count: 19, __typename: 'CountTuple' },
        { name: 'Sebastián Piana', count: 19, __typename: 'CountTuple' },
        { name: 'Ariel Pedernera', count: 18, __typename: 'CountTuple' },
        { name: "Edelmiro D'Amario", count: 18, __typename: 'CountTuple' },
        {
          name: 'Adolfo Rosquella/ Adolfo Rosquellas',
          count: 18,
          __typename: 'CountTuple',
        },
        { name: 'Roberto Garza', count: 18, __typename: 'CountTuple' },
        { name: 'Ricardo Pedevilla', count: 17, __typename: 'CountTuple' },
        { name: 'Carlos Demaria', count: 17, __typename: 'CountTuple' },
        {
          name: 'Quinteto Astor Piazzolla',
          count: 17,
          __typename: 'CountTuple',
        },
        { name: 'Tito Ribero', count: 17, __typename: 'CountTuple' },
        { name: 'José Sala', count: 16, __typename: 'CountTuple' },
        { name: 'Salvador Pizarro', count: 16, __typename: 'CountTuple' },
        { name: 'Al Tango', count: 16, __typename: 'CountTuple' },
        { name: 'Carlos Marcucci', count: 16, __typename: 'CountTuple' },
        { name: 'Atahualpa Yupanqui', count: 16, __typename: 'CountTuple' },
        { name: 'Ismael Spitalnik', count: 16, __typename: 'CountTuple' },
        { name: 'Celestino Ferrer', count: 16, __typename: 'CountTuple' },
        { name: 'Dante Puricelli', count: 16, __typename: 'CountTuple' },
        {
          name: 'Orquesta Matos Rodríguez',
          count: 15,
          __typename: 'CountTuple',
        },
        {
          name: 'Quinteto Francisco Canaro',
          count: 14,
          __typename: 'CountTuple',
        },
        { name: 'Ariel Ramírez', count: 14, __typename: 'CountTuple' },
        {
          name: "dir. Antonio D'Alessandro",
          count: 14,
          __typename: 'CountTuple',
        },
        { name: 'Trío Garufa', count: 14, __typename: 'CountTuple' },
        { name: 'Selección Nacional', count: 14, __typename: 'CountTuple' },
        { name: 'Leo Lipesker', count: 14, __typename: 'CountTuple' },
        { name: 'Atilio Stampone', count: 13, __typename: 'CountTuple' },
        {
          name: 'Mandragora Tango Orchestra',
          count: 13,
          __typename: 'CountTuple',
        },
        { name: 'Eduardo Rovira', count: 13, __typename: 'CountTuple' },
        { name: 'Jaime Vila', count: 13, __typename: 'CountTuple' },
        { name: 'Ángel Domínguez', count: 13, __typename: 'CountTuple' },
        {
          name: 'Estrellas de Buenos Aires',
          count: 12,
          __typename: 'CountTuple',
        },
        { name: 'Pablo Ziegler', count: 12, __typename: 'CountTuple' },
        { name: 'Victor Buchino', count: 12, __typename: 'CountTuple' },
        { name: 'Vicente Spina', count: 12, __typename: 'CountTuple' },
        { name: 'Eduardo Pereyra', count: 12, __typename: 'CountTuple' },
        { name: 'Alfredo Marcucci', count: 12, __typename: 'CountTuple' },
        { name: 'Héctor Arbelo', count: 12, __typename: 'CountTuple' },
        { name: 'dir. Osvaldo Requena', count: 12, __typename: 'CountTuple' },
        { name: 'Güerino Filipotto', count: 12, __typename: 'CountTuple' },
        {
          name: 'Orquesta Típica Decareana',
          count: 12,
          __typename: 'CountTuple',
        },
        { name: 'Romeo Gavioli', count: 11, __typename: 'CountTuple' },
        { name: 'Armando Baliotti', count: 11, __typename: 'CountTuple' },
        { name: 'Alejandro Scarpino', count: 11, __typename: 'CountTuple' },
        {
          name: 'Carlos Vicente Geroni Flores',
          count: 11,
          __typename: 'CountTuple',
        },
        { name: 'Vicente Loduca', count: 11, __typename: 'CountTuple' },
        { name: 'Marek Weber', count: 10, __typename: 'CountTuple' },
        { name: 'José Libertella', count: 10, __typename: 'CountTuple' },
        { name: 'Luis Nicolas Visca', count: 9, __typename: 'CountTuple' },
        {
          name: 'Enrique Santos Discépolo',
          count: 9,
          __typename: 'CountTuple',
        },
        { name: 'Nuevo Quinteto Real', count: 9, __typename: 'CountTuple' },
        { name: 'Vibratanghissimo', count: 9, __typename: 'CountTuple' },
        { name: 'Roberto Chanel', count: 9, __typename: 'CountTuple' },
        { name: 'Orestes Cúfaro', count: 9, __typename: 'CountTuple' },
        { name: 'Barnabás von Géczy', count: 9, __typename: 'CountTuple' },
        { name: "Victor D'Amario", count: 9, __typename: 'CountTuple' },
        { name: 'Augusto Pedro Berto', count: 9, __typename: 'CountTuple' },
        { name: 'Carlos Gardel', count: 9, __typename: 'CountTuple' },
        { name: 'Bernardo Alemany', count: 9, __typename: 'CountTuple' },
        { name: 'Roberto Casal', count: 8, __typename: 'CountTuple' },
        { name: 'Juan Cruz Mateo', count: 8, __typename: 'CountTuple' },
        { name: 'Dizzy Gillespie', count: 8, __typename: 'CountTuple' },
        { name: 'Luciano Leocata', count: 8, __typename: 'CountTuple' },
        { name: 'Victor Hugo Baralis', count: 8, __typename: 'CountTuple' },
        { name: 'Oskar Joost', count: 8, __typename: 'CountTuple' },
        { name: 'Juan Polito', count: 8, __typename: 'CountTuple' },
        {
          name: 'Orquesta Típica Fernández Fierro',
          count: 8,
          __typename: 'CountTuple',
        },
        { name: 'Rosendo Pesoa', count: 8, __typename: 'CountTuple' },
        { name: 'Tito Martín', count: 7, __typename: 'CountTuple' },
        { name: 'Luis Caruso', count: 7, __typename: 'CountTuple' },
        { name: 'Mario Melfi', count: 7, __typename: 'CountTuple' },
        { name: 'Eduardo Walter Stubbs', count: 7, __typename: 'CountTuple' },
        { name: 'Adalbert Lutter', count: 6, __typename: 'CountTuple' },
        { name: 'Roberto Pansera', count: 6, __typename: 'CountTuple' },
        { name: 'Juan Cao', count: 6, __typename: 'CountTuple' },
        { name: 'Jorge Fernández', count: 6, __typename: 'CountTuple' },
        { name: 'Julián Plaza', count: 6, __typename: 'CountTuple' },
        { name: 'Raúl Kaplún', count: 6, __typename: 'CountTuple' },
        { name: 'Francisco Troppoli', count: 6, __typename: 'CountTuple' },
        { name: 'Robert Gaden', count: 6, __typename: 'CountTuple' },
        { name: 'Manuel Romeo', count: 6, __typename: 'CountTuple' },
        { name: 'José Tinelli', count: 6, __typename: 'CountTuple' },
        { name: 'Emilio Pellejero', count: 6, __typename: 'CountTuple' },
        { name: 'Hugo Di Carlo', count: 6, __typename: 'CountTuple' },
        { name: 'Francisco Alongi', count: 6, __typename: 'CountTuple' },
        { name: 'Tango Diablo', count: 5, __typename: 'CountTuple' },
        { name: 'Juan Carlos Cambón', count: 5, __typename: 'CountTuple' },
        { name: 'Vieri Fidanzini', count: 5, __typename: 'CountTuple' },
        { name: 'José Lucchesi', count: 5, __typename: 'CountTuple' },
        { name: 'Salvador Grupillo', count: 5, __typename: 'CountTuple' },
        { name: 'Oscar Roma', count: 5, __typename: 'CountTuple' },
        { name: 'Alberto Alonso', count: 5, __typename: 'CountTuple' },
        { name: 'Porfirio Díaz', count: 5, __typename: 'CountTuple' },
        { name: 'Miguel Orlando', count: 5, __typename: 'CountTuple' },
        { name: 'Atilio Bruni', count: 5, __typename: 'CountTuple' },
        { name: "Nicolás D'Alessandro", count: 5, __typename: 'CountTuple' },
        { name: 'Miguel Nijensohn', count: 5, __typename: 'CountTuple' },
        { name: 'Enrique Lomuto', count: 5, __typename: 'CountTuple' },
        { name: 'Julio Ahumada', count: 4, __typename: 'CountTuple' },
        { name: 'Trío Victor', count: 4, __typename: 'CountTuple' },
        { name: 'Cristóbal Ramos', count: 4, __typename: 'CountTuple' },
        { name: 'Cuarteto del 900', count: 4, __typename: 'CountTuple' },
        {
          name: 'Edmundo Porteño Zaldivar',
          count: 4,
          __typename: 'CountTuple',
        },
        { name: 'Osvaldo Tarantino', count: 4, __typename: 'CountTuple' },
        { name: 'Rogelio Coll', count: 4, __typename: 'CountTuple' },
        { name: 'Domingo Rulio', count: 4, __typename: 'CountTuple' },
        { name: 'César Zagnoli', count: 4, __typename: 'CountTuple' },
        { name: 'Ernesto Franco', count: 4, __typename: 'CountTuple' },
        { name: 'Miguel Bonano', count: 4, __typename: 'CountTuple' },
        { name: 'dir. R. Garello', count: 4, __typename: 'CountTuple' },
        {
          name: 'Quinteto Los virtuosos',
          count: 4,
          __typename: 'CountTuple',
        },
        { name: 'Antonio Scatasso', count: 4, __typename: 'CountTuple' },
        { name: 'Martin Darré', count: 4, __typename: 'CountTuple' },
        { name: 'Osvaldo Cordó', count: 4, __typename: 'CountTuple' },
        { name: 'Rafael Rossi', count: 3, __typename: 'CountTuple' },
        { name: 'José Soler', count: 3, __typename: 'CountTuple' },
        { name: 'Juanjo Domínguez', count: 3, __typename: 'CountTuple' },
        { name: 'dir. Oscar Bassi', count: 3, __typename: 'CountTuple' },
        { name: 'José Luis Padula', count: 3, __typename: 'CountTuple' },
        { name: 'Alberto Gambino', count: 3, __typename: 'CountTuple' },
        { name: 'Diego Centeno', count: 3, __typename: 'CountTuple' },
        { name: 'Enrique Maciel', count: 3, __typename: 'CountTuple' },
        {
          name: 'Orquesta Radio Victor Argentina',
          count: 3,
          __typename: 'CountTuple',
        },
        { name: 'Enrique di Lorenzo', count: 3, __typename: 'CountTuple' },
        { name: 'Joaquín Mora', count: 3, __typename: 'CountTuple' },
        { name: 'René Pesenti', count: 3, __typename: 'CountTuple' },
        { name: 'Edmundo Rivero', count: 3, __typename: 'CountTuple' },
        {
          name: 'Cuarteto Victor de la Guardia Vieja',
          count: 3,
          __typename: 'CountTuple',
        },
        { name: 'Julian Fuhs', count: 3, __typename: 'CountTuple' },
        { name: 'Quintin Verdú', count: 2, __typename: 'CountTuple' },
        { name: 'Roberto Nievas Blanco', count: 2, __typename: 'CountTuple' },
        { name: 'Oscar Castagniaro', count: 2, __typename: 'CountTuple' },
        { name: 'Néstor Marconi', count: 2, __typename: 'CountTuple' },
        { name: 'Roberto Firpo (hijo)', count: 2, __typename: 'CountTuple' },
        { name: 'Quinteto Real', count: 2, __typename: 'CountTuple' },
        {
          name: 'Orquesta Típica Columbia',
          count: 2,
          __typename: 'CountTuple',
        },
        { name: 'Roberto Luratti', count: 2, __typename: 'CountTuple' },
        { name: 'Anibal Arias', count: 2, __typename: 'CountTuple' },
        { name: 'Daniel Melingo', count: 2, __typename: 'CountTuple' },
        { name: 'Osvaldo José Montes', count: 2, __typename: 'CountTuple' },
        { name: 'Los Indios Tacunao', count: 2, __typename: 'CountTuple' },
        { name: 'Francisco Spaventa', count: 2, __typename: 'CountTuple' },
        { name: 'Américo Belloto', count: 2, __typename: 'CountTuple' },
        { name: 'Pascual Elía', count: 2, __typename: 'CountTuple' },
        { name: 'Tity Quentin', count: 2, __typename: 'CountTuple' },
        { name: 'Rubén Sosa', count: 2, __typename: 'CountTuple' },
        { name: 'Domingo Marafioti', count: 2, __typename: 'CountTuple' },
        { name: 'Francisco Maquiera', count: 2, __typename: 'CountTuple' },
        { name: 'Alberto Gómez', count: 2, __typename: 'CountTuple' },
        { name: 'Hugo Piro', count: 2, __typename: 'CountTuple' },
        { name: 'Los Astros del Tango', count: 2, __typename: 'CountTuple' },
        { name: 'Alberto Caracciolo', count: 2, __typename: 'CountTuple' },
        { name: 'Daniel Lomuto', count: 2, __typename: 'CountTuple' },
        { name: 'Ángel Villoldo', count: 2, __typename: 'CountTuple' },
        { name: 'Alfredo De Franco', count: 2, __typename: 'CountTuple' },
        { name: 'Juan Llossas', count: 2, __typename: 'CountTuple' },
        { name: 'Rafael Iriarte', count: 2, __typename: 'CountTuple' },
        {
          name: 'Orquesta Típica Ciriaquito',
          count: 2,
          __typename: 'CountTuple',
        },
        { name: 'Alberto Castillo', count: 2, __typename: 'CountTuple' },
        { name: 'Alfredo E. Gobbi', count: 2, __typename: 'CountTuple' },
        { name: 'Julio Espindola', count: 2, __typename: 'CountTuple' },
        { name: 'Antonio Arcieri', count: 2, __typename: 'CountTuple' },
        { name: 'Charlo', count: 2, __typename: 'CountTuple' },
        { name: 'Elvino Vardaro', count: 2, __typename: 'CountTuple' },
        { name: 'Ángel Sica', count: 2, __typename: 'CountTuple' },
        { name: 'Vicente Demarco', count: 1, __typename: 'CountTuple' },
        { name: 'Alberto Soifer', count: 1, __typename: 'CountTuple' },
        { name: 'Cátulo Castillo', count: 1, __typename: 'CountTuple' },
        { name: 'Los Tubatango', count: 1, __typename: 'CountTuple' },
        { name: 'Carlos Ramón Lobos', count: 1, __typename: 'CountTuple' },
        { name: 'Manuel Campoamor', count: 1, __typename: 'CountTuple' },
        { name: 'Antonio Buglione', count: 1, __typename: 'CountTuple' },
        { name: 'Hugo del Carril', count: 1, __typename: 'CountTuple' },
        { name: 'Carlos Ángel Lázzari', count: 1, __typename: 'CountTuple' },
        { name: 'Antonio Sureda', count: 1, __typename: 'CountTuple' },
        { name: 'Omar José Murtagh', count: 1, __typename: 'CountTuple' },
        {
          name: 'Orquesta Escuela de tango',
          count: 1,
          __typename: 'CountTuple',
        },
        { name: 'Héctor Mauré', count: 1, __typename: 'CountTuple' },
        {
          name: 'Quinteto Criollo Atlana',
          count: 1,
          __typename: 'CountTuple',
        },
        { name: 'Horacio Malvicino', count: 1, __typename: 'CountTuple' },
        { name: 'Alberto Echagüe', count: 1, __typename: 'CountTuple' },
        { name: 'Felice Verrecchia', count: 1, __typename: 'CountTuple' },
        { name: 'Panchito Cao', count: 1, __typename: 'CountTuple' },
        { name: 'Alberto Vila', count: 1, __typename: 'CountTuple' },
        { name: 'Ernesto de la Cruz', count: 1, __typename: 'CountTuple' },
        { name: 'Miguel Montero', count: 1, __typename: 'CountTuple' },
        { name: 'María Graña', count: 1, __typename: 'CountTuple' },
        { name: 'José Ángel Trelles', count: 1, __typename: 'CountTuple' },
        { name: 'Ramón Rosa Lobos', count: 1, __typename: 'CountTuple' },
        { name: 'Osvaldo Piro', count: 1, __typename: 'CountTuple' },
        { name: 'Beba Pugliese', count: 1, __typename: 'CountTuple' },
        { name: 'dir. Astor Bolognini', count: 1, __typename: 'CountTuple' },
        { name: 'Juan Carlos Cuacci', count: 1, __typename: 'CountTuple' },
        { name: 'José Razzano', count: 1, __typename: 'CountTuple' },
        { name: 'Libertad Lamarque', count: 1, __typename: 'CountTuple' },
        { name: 'Dajos Béla', count: 1, __typename: 'CountTuple' },
        { name: 'Mario Alberto Pardo', count: 1, __typename: 'CountTuple' },
        { name: 'José Colángelo', count: 1, __typename: 'CountTuple' },
        { name: 'Horacio Arturo Ferrer', count: 1, __typename: 'CountTuple' },
        { name: 'Gustavo Nocetti', count: 1, __typename: 'CountTuple' },
        { name: 'Pedro Noda', count: 1, __typename: 'CountTuple' },
      ],
      genre: [
        { name: 'tango', count: 18379, __typename: 'CountTuple' },
        { name: 'vals', count: 2037, __typename: 'CountTuple' },
        { name: 'milonga', count: 971, __typename: 'CountTuple' },
        { name: 'unknown', count: 687, __typename: 'CountTuple' },
        { name: 'fox trot', count: 426, __typename: 'CountTuple' },
        { name: 'ranchera', count: 411, __typename: 'CountTuple' },
        { name: 'paso doble', count: 382, __typename: 'CountTuple' },
        { name: 'canción', count: 208, __typename: 'CountTuple' },
        { name: 'zamba', count: 95, __typename: 'CountTuple' },
        { name: 'marcha', count: 90, __typename: 'CountTuple' },
        { name: 'estilo', count: 82, __typename: 'CountTuple' },
        { name: 'polca', count: 72, __typename: 'CountTuple' },
        { name: 'candombe', count: 57, __typename: 'CountTuple' },
        { name: 'rumba', count: 55, __typename: 'CountTuple' },
        { name: 'shimmy', count: 50, __typename: 'CountTuple' },
        { name: 'corrido', count: 47, __typename: 'CountTuple' },
        { name: 'milonga candombe', count: 43, __typename: 'CountTuple' },
        { name: 'maxixa', count: 39, __typename: 'CountTuple' },
        { name: 'tonada', count: 35, __typename: 'CountTuple' },
        { name: 'fado', count: 17, __typename: 'CountTuple' },
        { name: 'chacarera', count: 16, __typename: 'CountTuple' },
        { name: 'potpourri', count: 15, __typename: 'CountTuple' },
        { name: 'bolero', count: 14, __typename: 'CountTuple' },
        { name: 'gato', count: 13, __typename: 'CountTuple' },
        { name: 'tarantela', count: 13, __typename: 'CountTuple' },
        { name: 'cueca', count: 13, __typename: 'CountTuple' },
        { name: 'speech', count: 9, __typename: 'CountTuple' },
        { name: 'habanera', count: 9, __typename: 'CountTuple' },
        { name: 'cifra', count: 8, __typename: 'CountTuple' },
        { name: 'pericón', count: 8, __typename: 'CountTuple' },
        { name: 'conga', count: 8, __typename: 'CountTuple' },
        { name: 'bailecito', count: 7, __typename: 'CountTuple' },
        { name: 'maxixe', count: 7, __typename: 'CountTuple' },
      ],
      __typename: 'SelectIndexCount',
    },
    __typename: 'CompoundResults',
  },
};
