import { TrackDetailsBatchQuery } from '../../../generated/graphql';

export const trackDetailsBatch: TrackDetailsBatchQuery = {
  tracksByIds: [
    {
      id: '10688',
      title: 'A Belisario Roldán',
      genre: 'tango',
      singer: ['Instrumental'],
      orchestra: ['Pedro Laurenz'],
      secondsLong: 183,
      year: 1953,
      linkScore: 9,
      link: {
        description:
          'Composed by Enrique Forte: A Tribute to Belisario Roldán Belisario Roldán (Buenos Aires, 1873 - Alta Gracia, 1922) Poet, ...',
        title: 'A Belisario Roldán: 1953 Pedro Laurenz',
        videoId: 'D7KHcBIf-og',
        __typename: 'RatedYoutube',
      },
      __typename: 'SimpleTrack',
    },
    {
      id: '10696',
      title: 'A Don Antonio',
      genre: 'tango',
      singer: ['Instrumental'],
      orchestra: ['Héctor Varela'],
      secondsLong: 163,
      year: 1964,
      linkScore: 8,
      link: {
        description:
          'Provided to YouTube by The Orchard Enterprises A Don Antonio · Orquesta de Héctor Varela · Héctor Varela Vareleando ℗ 2015 ...',
        title: 'A Don Antonio',
        videoId: 'M8WktSxqX_Q',
        __typename: 'RatedYoutube',
      },
      __typename: 'SimpleTrack',
    },
    {
      id: '10698',
      title: 'A Don Héctor María',
      genre: 'tango',
      singer: ['Instrumental'],
      orchestra: ['Héctor Varela'],
      secondsLong: 161,
      year: 1973,
      linkScore: 4,
      link: {
        description: '',
        title: 'Don Goyo-- Héctor Varela',
        videoId: 'towG9esdSO0',
        __typename: 'RatedYoutube',
      },
      __typename: 'SimpleTrack',
    },
    {
      id: '10699',
      title: 'A Don Agustín Bardi',
      genre: 'tango',
      singer: ['Instrumental'],
      orchestra: ['Ensemble Hyperion'],
      secondsLong: 195,
      year: 2007,
      linkScore: 6,
      link: {
        description:
          'Provided to YouTube by Zebralution GmbH A Don Agustin Bardi · Hyperion Ensemble Buenos Aires hora cero ℗ 2007 Viamas ...',
        title: 'A Don Agustin Bardi',
        videoId: 'iVRGOkIqrDU',
        __typename: 'RatedYoutube',
      },
      __typename: 'SimpleTrack',
    },
    {
      id: '10700',
      title: 'A Don Horacio',
      genre: 'tango',
      singer: ['Instrumental'],
      orchestra: ['Alberto Oscar Gentile'],
      secondsLong: 147,
      year: 1950,
      linkScore: 1,
      link: {
        description:
          'Dupla arrasadora del Tango, Alfredo De Angelis y la voz del cantor Oscar Larroca. Festival de éxitos. 1) Volvamos a empezar ...',
        title:
          'ALFREDO DE ANGELIS - OSCAR LARROCA - 12 GRANDES EXITOS Vol. 1 - por CANTANDO TANGOS 1951 / 1958',
        videoId: 'TzPOKPPCLNo',
        __typename: 'RatedYoutube',
      },
      __typename: 'SimpleTrack',
    },
    {
      id: '10701',
      title: 'A Don Claudio',
      genre: 'tango',
      singer: ['Instrumental'],
      orchestra: ['Miguel Villasboas'],
      secondsLong: 150,
      year: 2001,
      linkScore: 8,
      link: {
        description:
          'Provided to YouTube by The Orchard Enterprises A Don Claudio · Miguel Villasboas y Su Orquesta Típica En Japón ℗ 2002 ...',
        title: 'A Don Claudio',
        videoId: 'LC_daDyDIb4',
        __typename: 'RatedYoutube',
      },
      __typename: 'SimpleTrack',
    },
    {
      id: '10702',
      title: 'A Don Pedro Maffia | A Pedro Maffia',
      genre: 'tango',
      singer: ['Instrumental'],
      orchestra: ['Aníbal Troilo'],
      secondsLong: 182,
      year: 1968,
      linkScore: 9,
      link: {
        description: 'https://www.facebook.com/djtorotango.',
        title: 'Anibal Troilo - 1968 - Cuarteto - A Pedro Maffia',
        videoId: 'w8320CMlPpc',
        __typename: 'RatedYoutube',
      },
      __typename: 'SimpleTrack',
    },
    {
      id: '10703',
      title: 'A Don Pedro Maffia | A Pedro Maffia',
      genre: 'tango',
      singer: ['Instrumental'],
      orchestra: ['Cuarteto Troilo-Grela'],
      secondsLong: 172,
      year: 1953,
      linkScore: 5,
      link: {
        description: '',
        title: 'Troilo y Grela - A Pedro Maffia',
        videoId: '75OJ13PoIC8',
        __typename: 'RatedYoutube',
      },
      __typename: 'SimpleTrack',
    },
    {
      id: '10707',
      title: 'A España',
      genre: 'paso doble',
      singer: ['Alberto Castillo'],
      orchestra: ['Ángel F. Condercuri'],
      secondsLong: 130,
      year: 1956,
      linkScore: 6,
      link: {
        description:
          'Alberto Castillo (7 de diciembre de 1914 -- 23 de julio de 2002) fue un prominente cantor de tango y actor argentino. Nació como ...',
        title: 'Alberto Castillo -- A España Pasodoble',
        videoId: 'xMSAleSAlFo',
        __typename: 'RatedYoutube',
      },
      __typename: 'SimpleTrack',
    },
    {
      id: '10708',
      title: 'A Don Horacio Salgán',
      genre: 'tango',
      singer: ['Instrumental'],
      orchestra: ['Orquesta Puglia-Pedroza'],
      secondsLong: 201,
      year: 1952,
      linkScore: 6,
      link: {
        description:
          'Tanda di tango Orquesta Puglia Pedroza 1952 A Don Horacio Salgán Mosquita Viejo Parque Patricios Nueve puntos.',
        title: 'Tanda di tango Orquesta Puglia Pedroza  1952',
        videoId: '0E_v8Nz-4g0',
        __typename: 'RatedYoutube',
      },
      __typename: 'SimpleTrack',
    },
    {
      id: '10710',
      title: 'A Evaristo Carriego',
      genre: 'tango',
      singer: ['Instrumental'],
      orchestra: ['Osvaldo Pugliese'],
      secondsLong: 230,
      year: 1969,
      linkScore: 9,
      link: {
        description:
          'A Evaristo Carriego Compositor: Eduardo Rovira Año de grabación: 1966 https://www.youtube.com/watch?v=665X8YCF-Hc.',
        title: 'A Evaristo Carriego - Orquesta Osvaldo Pugliese 1969',
        videoId: '3N7MhkhlWBs',
        __typename: 'RatedYoutube',
      },
      __typename: 'SimpleTrack',
    },
    {
      id: '10711',
      title: 'A Evaristo Carriego',
      genre: 'tango',
      singer: ['Instrumental'],
      orchestra: ['Osvaldo Pugliese'],
      secondsLong: 260,
      year: 1985,
      linkScore: 9,
      link: {
        description:
          'Pugliese y su orquesta ejecutan "A Evaristo Carriego" de Eduardo Rovira en el Teatro Colón del 26 de diciembre de 1985.',
        title: 'A Evaristo Carriego - Osvaldo Pugliese (Teatro Colón 1985)',
        videoId: 'imlf-BR7J9w',
        __typename: 'RatedYoutube',
      },
      __typename: 'SimpleTrack',
    },
    {
      id: '10712',
      title: 'A Evaristo Carriego',
      genre: 'tango',
      singer: ['Instrumental'],
      orchestra: ['Osvaldo Pugliese'],
      secondsLong: 429,
      year: 1989,
      linkScore: 8,
      link: {
        description: 'OSVALDO PUGLIESE.',
        title: 'A EVARISTO CARRIEGO - PUGLIESE',
        videoId: 'UTD3ntFNx0w',
        __typename: 'RatedYoutube',
      },
      __typename: 'SimpleTrack',
    },
    {
      id: '10713',
      title: 'A Evaristo Carriego',
      genre: 'tango',
      singer: ['Instrumental'],
      orchestra: ['Ensemble Hyperion'],
      secondsLong: 232,
      year: 2005,
      linkScore: 6,
      link: {
        description:
          'Provided to YouTube by Zebralution GmbH A Evaristo Carriego · Hyperion Ensemble Corso Buenos Aires ℗ 2005 Viamas GmbH ...',
        title: 'A Evaristo Carriego',
        videoId: 'tPewckZIgFA',
        __typename: 'RatedYoutube',
      },
      __typename: 'SimpleTrack',
    },
    {
      id: '10714',
      title: 'A Evaristo Carriego',
      genre: 'tango',
      singer: ['Instrumental'],
      orchestra: ['QuinTango'],
      secondsLong: 288,
      year: 2008,
      linkScore: 9,
      link: {
        description:
          'Provided to YouTube by The Orchard Enterprises A Evaristo Carriego · QuinTango Triunfal ℗ 2008 Quintango Released on: ...',
        title: 'A Evaristo Carriego',
        videoId: 'yc-H9b2c4ZE',
        __typename: 'RatedYoutube',
      },
      __typename: 'SimpleTrack',
    },
    {
      id: '10715',
      title: 'A Francini / Pontier',
      genre: 'tango',
      singer: ['Instrumental'],
      orchestra: ['Orquesta Puglia-Pedroza'],
      secondsLong: 175,
      year: 1952,
      linkScore: 5,
      link: {
        description:
          'Provided to YouTube by The Orchard Enterprises A Francini / Pontier · Orquesta Puglia Pedroza Tangostalgía (Desde la Memoria.',
        title: 'A Francini / Pontier',
        videoId: '-u1UcrrU9Cc',
        __typename: 'RatedYoutube',
      },
      __typename: 'SimpleTrack',
    },
    {
      id: '10727',
      title: 'A Guaminí',
      genre: 'vals',
      singer: ['Nelly Omar'],
      orchestra: ['José Canet'],
      secondsLong: 156,
      year: 1979,
      linkScore: 5,
      link: {
        description:
          'Nelly Omar Nelly Omar con la Orquesta de José Canet Embassy (11) – 90.010 1977 TEMAS: 01 El Dia Que Me Quieras 02 Rosas ...',
        title: 'Nelly Omar - Nelly Omar con la orquesta de José Canet   (1977)',
        videoId: '5tpFlsNWkSA',
        __typename: 'RatedYoutube',
      },
      __typename: 'SimpleTrack',
    },
    {
      id: '10729',
      title: 'A Homero',
      genre: 'tango',
      singer: ['Roberto Goyeneche'],
      orchestra: ['Aníbal Troilo'],
      secondsLong: 197,
      year: 1961,
      linkScore: 8,
      link: {
        description: 'https://www.facebook.com/djtorotango.',
        title: 'Anibal Troilo - 1961 - Goyeneche - A Homero',
        videoId: 'Tcj0AnqpHLc',
        __typename: 'RatedYoutube',
      },
      __typename: 'SimpleTrack',
    },
    {
      id: '10732',
      title: 'A Jorge Páez Vilaró',
      genre: 'tango',
      singer: ['Instrumental'],
      orchestra: ['Miguel Villasboas'],
      secondsLong: 144,
      year: 1972,
      linkScore: 8,
      link: {
        description:
          'Provided to YouTube by The Orchard Enterprises A Jorge Páez Vilaró · Miguel Villasboas y Su Orquesta Tìpica En Nueva York ...',
        title: 'A Jorge Páez Vilaró',
        videoId: 'IGeGUR9afvs',
        __typename: 'RatedYoutube',
      },
      __typename: 'SimpleTrack',
    },
    {
      id: '10733',
      title: 'A Homero',
      genre: 'tango',
      singer: ['Ricardo Olivera'],
      orchestra: ['Unknown'],
      secondsLong: 211,
      year: 2009,
      linkScore: 7,
      link: {
        description:
          'Provided to YouTube by The Orchard Enterprises A Homero · Ricardo Olivera & Alvaro Hagopián Trío Aristocracia Arrabalera ...',
        title: 'A Homero',
        videoId: 'm-N_WRLNx1I',
        __typename: 'RatedYoutube',
      },
      __typename: 'SimpleTrack',
    },
  ],
};
