query CompoundQuery($criteria: CompoundQueryInput!) {
  compoundQuery(query: $criteria) {
    ids
    totalResults
    ...FullCountFragment
  }
}

fragment FullCountFragment on CompoundResults {
  counts {
    year {
      name
      count
    }
    singer {
      name
      count
    }
    orchestra {
      name
      count
    }
    genre {
      name
      count
    }
  }
}
