#!/bin/bash
source /home/ec2-user/bash_profile_generic
chown -R ec2-user /home/ec2-user/app
npm install -g pm2
cp /home/ec2-user/app_env /home/ec2-user/app/projects/api/.env
pm2 start /home/ec2-user/app/projects/api/ecosystem.config.js
