import { TrackDetailFragmentFragment } from '../../../generated/graphql';

export const darienzoLaborde: Array<TrackDetailFragmentFragment> = [
  {
    id: '40',
    title: 'Bailarín compadrito',
    genre: 'tango',
    singer: ['Armando Laborde'],
    orchestra: ["Juan D'Arienzo"],
    flaggedForRescrape: true,
    secondsLong: 165,
    year: 1973,
    linkScore: 8,
    link: {
      description: 'https://www.facebook.com/djtorotango.',
      title: "Juan D'arienzo - 1973 - Laborde - Bailarin compadrito",
      videoId: 'YcaHCEErcl0',
      __typename: 'RatedYoutube',
    },
    __typename: 'SimpleTrack',
  },
  {
    id: '121',
    title: 'Bandera baja',
    genre: 'milonga',
    singer: ['Alberto Echagüe'],
    orchestra: ["Juan D'Arienzo"],
    flaggedForRescrape: true,
    secondsLong: 140,
    year: 1950,
    linkScore: 10,
    link: {
      description: "Juan D'Arienzo Alberto Echague Bandera baja 1950.",
      title: "Juan D'Arienzo  Alberto Echague    Bandera baja   1950",
      videoId: 'pN7mvcBuTwQ',
      __typename: 'RatedYoutube',
    },
    __typename: 'SimpleTrack',
  },
  {
    id: '10937',
    title: 'A mi vieja',
    genre: 'tango',
    singer: ['Armando Laborde'],
    orchestra: ["Juan D'Arienzo"],
    flaggedForRescrape: true,
    secondsLong: null,
    year: 1968,
    linkScore: 8,
    link: {
      description: 'https://www.facebook.com/djtorotango.',
      title: "Juan D'arienzo - 1968 - Laborde - A mi vieja",
      videoId: 'Vun4ye75l8o',
      __typename: 'RatedYoutube',
    },
    __typename: 'SimpleTrack',
  },
  {
    id: '10984',
    title: 'A puño limpio',
    genre: 'milonga',
    singer: ['Alberto Echagüe'],
    orchestra: ["Juan D'Arienzo"],
    flaggedForRescrape: true,
    secondsLong: 151,
    year: 1950,
    linkScore: 10,
    link: {
      description:
        "A pedido la milonga A PUÑO LIMPIO por la orquesta tipica de JUAN D'ARIENZO y ALBERTO ECHAGUE.",
      title:
        "JUAN D'ARIENZO - ALBERTO ECHAGUE - A PUÑO LIMPIO - MILONGA - 1950",
      videoId: 'rInUdQsqyu8',
      __typename: 'RatedYoutube',
    },
    __typename: 'SimpleTrack',
  },
  {
    id: '11010',
    title: 'A suerte y verdad',
    genre: 'tango',
    singer: ['Alberto Echagüe'],
    orchestra: ["Juan D'Arienzo"],
    flaggedForRescrape: true,
    secondsLong: 154,
    year: 1944,
    linkScore: 8,
    link: {
      description: 'https://www.facebook.com/djtorotango.',
      title: "Juan D'Arienzo - 1944 - Echague - A suerte y verdad",
      videoId: 'upZThAY7P7o',
      __typename: 'RatedYoutube',
    },
    __typename: 'SimpleTrack',
  },
  {
    id: '11088',
    title: 'Aclaremos',
    genre: 'tango',
    singer: ['Armando Laborde'],
    orchestra: ["Juan D'Arienzo"],
    flaggedForRescrape: true,
    secondsLong: 197,
    year: 1956,
    linkScore: 8,
    link: {
      description: 'https://www.facebook.com/djtorotango.',
      title: "Juan D'arienzo - 1956 - Laborde - Aclaremos",
      videoId: 'Y9k-x20-gOY',
      __typename: 'RatedYoutube',
    },
    __typename: 'SimpleTrack',
  },
  {
    id: '11350',
    title: 'Ahí está',
    genre: 'tango',
    singer: ['Armando Laborde'],
    orchestra: ["Juan D'Arienzo"],
    flaggedForRescrape: true,
    secondsLong: 174,
    year: 1954,
    linkScore: 10,
    link: {
      description:
        "14 de Diciembre de 1900 nacia el maestro JUAN D'ARIENZO. El tango es patrimonio de la humanidad gracias a obras como las ...",
      title: "JUAN D'ARIENZO - ARMANDO LABORDE - AHI ESTA - TANGO - 1954",
      videoId: 'BWj47CKodb0',
      __typename: 'RatedYoutube',
    },
    __typename: 'SimpleTrack',
  },
  {
    id: '11748',
    title: 'Amarga sospecha',
    genre: 'tango',
    singer: ['Armando Laborde'],
    orchestra: ["Juan D'Arienzo"],
    flaggedForRescrape: true,
    secondsLong: 165,
    year: 1949,
    linkScore: 8,
    link: {
      description: 'https://www.facebook.com/djtorotango.',
      title: "Juan D'arienzo - 1949 - Laborde - Amarga sospecha",
      videoId: 'BEvpwsCqWVk',
      __typename: 'RatedYoutube',
    },
    __typename: 'SimpleTrack',
  },
  {
    id: '11774',
    title: 'Amarroto',
    genre: 'tango',
    singer: ['Alberto Echagüe'],
    orchestra: ["Juan D'Arienzo"],
    flaggedForRescrape: true,
    secondsLong: 182,
    year: 1951,
    linkScore: 9,
    link: {
      description: '',
      title: 'JUAN DARIENZO ALBERTO ECHAGUE  AMARROTO',
      videoId: 'iG9BGdsLXBA',
      __typename: 'RatedYoutube',
    },
    __typename: 'SimpleTrack',
  },
  {
    id: '11840',
    title: 'Amor de fortinera',
    genre: 'milonga',
    singer: ['Armando Laborde', 'Osvaldo Ramos'],
    orchestra: ["Juan D'Arienzo"],
    flaggedForRescrape: true,
    secondsLong: null,
    year: 1966,
    linkScore: 8,
    link: {
      description: 'https://www.facebook.com/djtorotango.',
      title: "Juan D'arienzo - 1966 - Ramos y Laborde - Amor de fortinera",
      videoId: 'T-VU_84g9UU',
      __typename: 'RatedYoutube',
    },
    __typename: 'SimpleTrack',
  },
  {
    id: '11977',
    title: 'Andanzas',
    genre: 'tango',
    singer: ['Alberto Echagüe'],
    orchestra: ["Juan D'Arienzo"],
    flaggedForRescrape: true,
    secondsLong: 156,
    year: 1945,
    linkScore: 8,
    link: {
      description: 'https://www.facebook.com/djtorotango.',
      title: "Juan D'Arienzo - 1945 - Echague - Andanzas",
      videoId: 'fn8ZytLozpw',
      __typename: 'RatedYoutube',
    },
    __typename: 'SimpleTrack',
  },
  {
    id: '12089',
    title: 'Ansiedad',
    genre: 'tango',
    singer: ['Alberto Echagüe'],
    orchestra: ["Juan D'Arienzo"],
    flaggedForRescrape: true,
    secondsLong: 164,
    year: 1938,
    linkScore: 10,
    link: {
      description: 'https://www.facebook.com/djtorotango.',
      title: "Juan D'Arienzo - 1938 - Alberto Echague - Ansiedad",
      videoId: 'pPQHCUrW_rc',
      __typename: 'RatedYoutube',
    },
    __typename: 'SimpleTrack',
  },
  {
    id: '12108',
    title: 'Aparcero',
    genre: 'tango',
    singer: ['Armando Laborde', 'Alberto Echagüe'],
    orchestra: ["Juan D'Arienzo"],
    flaggedForRescrape: true,
    secondsLong: 174,
    year: 1945,
    linkScore: 8,
    link: {
      description: 'https://www.facebook.com/djtorotango.',
      title: "Juan D'Arienzo - 1945 - Echague Laborde - Aparcero",
      videoId: 'RBppoRmgJqI',
      __typename: 'RatedYoutube',
    },
    __typename: 'SimpleTrack',
  },
  {
    id: '12212',
    title: 'Aquí he venido a cantar',
    genre: 'tango',
    singer: ['Armando Laborde'],
    orchestra: ["Juan D'Arienzo"],
    flaggedForRescrape: true,
    secondsLong: 173,
    year: 1945,
    linkScore: 8,
    link: {
      description: 'https://www.facebook.com/djtorotango.',
      title: "Juan D'Arienzo - 1945 - Laborde - Aqui he venido a cantar",
      videoId: 'AQsS0YPBK2I',
      __typename: 'RatedYoutube',
    },
    __typename: 'SimpleTrack',
  },
  {
    id: '12245',
    title: 'Argañaráz',
    genre: 'tango',
    singer: ['Armando Laborde'],
    orchestra: ["Juan D'Arienzo"],
    flaggedForRescrape: true,
    secondsLong: null,
    year: 1966,
    linkScore: 8,
    link: {
      description: 'https://www.facebook.com/djtorotango.',
      title: "Juan D'arienzo - 1966 - Laborde - Argañaraz",
      videoId: 'ZRRNXbRzW0o',
      __typename: 'RatedYoutube',
    },
    __typename: 'SimpleTrack',
  },
  {
    id: '12346',
    title: 'Arrorro nené',
    genre: 'tango',
    singer: ['Armando Laborde'],
    orchestra: ["Juan D'Arienzo"],
    flaggedForRescrape: true,
    secondsLong: null,
    year: 1966,
    linkScore: 4,
    link: {
      description: 'https://www.facebook.com/djtorotango.',
      title: "Juan D'arienzo - 1966 - Laborde - Arroro nene",
      videoId: 'lAuo-abwd44',
      __typename: 'RatedYoutube',
    },
    __typename: 'SimpleTrack',
  },
  {
    id: '12537',
    title: 'Avivate pipistrelo',
    genre: 'tango',
    singer: ['Alberto Echagüe'],
    orchestra: ["Juan D'Arienzo"],
    flaggedForRescrape: true,
    secondsLong: 158,
    year: 1955,
    linkScore: 8,
    link: {
      description: '',
      title: "Juan D'arienzo - 1955 - Echague - Avivate pipistrelo",
      videoId: 'IjhXVZkZiyA',
      __typename: 'RatedYoutube',
    },
    __typename: 'SimpleTrack',
  },
  {
    id: '12542',
    title: 'Ay mimosa!',
    genre: 'tango',
    singer: ['Armando Laborde'],
    orchestra: ["Juan D'Arienzo"],
    flaggedForRescrape: true,
    secondsLong: 210,
    year: 1956,
    linkScore: 9,
    link: {
      description: '',
      title: 'Juan D´Arienzo - Armando Laborde - AY! MIMOSA',
      videoId: '078-UlErv8g',
      __typename: 'RatedYoutube',
    },
    __typename: 'SimpleTrack',
  },
  {
    id: '12555',
    title: 'Ay, aurora',
    genre: 'vals',
    singer: ['Alberto Echagüe'],
    orchestra: ["Juan D'Arienzo"],
    flaggedForRescrape: true,
    secondsLong: 138,
    year: 1939,
    linkScore: 10,
    link: {
      description: '',
      title: "Juan D'Arienzo - 1939 - Alberto Echague - Ay Aurora",
      videoId: 'o_7Bx9aIkxQ',
      __typename: 'RatedYoutube',
    },
    __typename: 'SimpleTrack',
  },
  {
    id: '12558',
    title: 'Ay, Aurora!',
    genre: 'vals',
    singer: ['Alberto Echagüe'],
    orchestra: ["Juan D'Arienzo"],
    flaggedForRescrape: true,
    secondsLong: null,
    year: 1973,
    linkScore: 8,
    link: {
      description: '',
      title: "Juan D'arienzo - 1973 - Echague - Ay Aurora",
      videoId: 'ipWYgiFj8Ds',
      __typename: 'RatedYoutube',
    },
    __typename: 'SimpleTrack',
  },
];
